import '../new_releases_screen/widgets/newreleases_item_widget.dart';import 'models/newreleases_item_model.dart';import 'notifier/new_releases_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';class NewReleasesScreen extends ConsumerStatefulWidget {const NewReleasesScreen({Key? key}) : super(key: key);

@override NewReleasesScreenState createState() =>  NewReleasesScreenState();

 }
class NewReleasesScreenState extends ConsumerState<NewReleasesScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 31.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_the_best_new_releases".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 16.v), _buildNewReleases(context), SizedBox(height: 36.v), _buildFortyNine(context), SizedBox(height: 15.v), _buildPositions(context, image: ImageConstant.imgImage44, positions: "lbl_pain".tr, arianaGrande: "lbl_ryan_jones".tr, image1: ImageConstant.imgImage45, positions1: "lbl_shades_of_love".tr, arianaGrande1: "lbl_ania_szarmach".tr)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_new_releases".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildNewReleases(BuildContext context) { return SizedBox(height: 242.v, child: Consumer(builder: (context, ref, _) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: ref.watch(newReleasesNotifier).newReleasesModelObj?.newreleasesItemList.length ?? 0, itemBuilder: (context, index) {NewreleasesItemModel model = ref.watch(newReleasesNotifier).newReleasesModelObj?.newreleasesItemList[index] ?? NewreleasesItemModel(); return NewreleasesItemWidget(model);});})); } 
/// Section Widget
Widget _buildFortyNine(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_new_albums_single".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildPositions(context, image: ImageConstant.imgImage42, positions: "lbl_pain".tr, arianaGrande: "lbl_ryan_jones".tr, image1: ImageConstant.imgImage43, positions1: "lbl_shades_of_love".tr, arianaGrande1: "lbl_ania_szarmach".tr)]); } 
/// Common widget
Widget _buildPositions(BuildContext context, {required String image, required String positions, required String arianaGrande, required String image1, required String positions1, required String arianaGrande1, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: image, height: 184.adaptSize, width: 184.adaptSize, radius: BorderRadius.circular(28.h)), SizedBox(height: 12.v), Text(positions, style: theme.textTheme.titleLarge!.copyWith(color: appTheme.gray90001)), SizedBox(height: 7.v), Text(arianaGrande, style: CustomTextStyles.titleSmallGray70001.copyWith(color: appTheme.gray70001))]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: image1, height: 184.adaptSize, width: 184.adaptSize, radius: BorderRadius.circular(28.h)), SizedBox(height: 11.v), Text(positions1, style: theme.textTheme.titleLarge!.copyWith(color: appTheme.gray90001)), SizedBox(height: 5.v), Text(arianaGrande1, style: CustomTextStyles.titleSmallGray70001.copyWith(color: appTheme.gray70001))])))]); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
