import 'models/language_model.dart';import 'package:flutter/material.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/custom_radio_button.dart';import 'provider/language_provider.dart';class LanguageScreen extends StatefulWidget {const LanguageScreen({Key? key}) : super(key: key);

@override LanguageScreenState createState() =>  LanguageScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => LanguageProvider(), child: LanguageScreen()); } 
 }
class LanguageScreenState extends State<LanguageScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_suggested".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 22.v), _buildSuggested(context), SizedBox(height: 30.v), Divider(), SizedBox(height: 30.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_others".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 23.v), _buildOthers(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "lbl_language".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSuggested(BuildContext context) { return Consumer<LanguageProvider>(builder: (context, provider, child) {return provider.languageModelObj!.radioList.isNotEmpty ? Column(children: [CustomRadioButton(width: 380.h, text: "lbl_english_us".tr, value: provider.languageModelObj?.radioList[0] ?? "", groupValue: provider.suggested, isRightCheck: true, onChange: (value) {provider.changeRadioButton1(value);}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_english_uk".tr, value: provider.languageModelObj?.radioList[1] ?? "", groupValue: provider.suggested, isRightCheck: true, onChange: (value) {provider.changeRadioButton1(value);}))]) : Container();}); } 
/// Section Widget
Widget _buildOthers(BuildContext context) { return Consumer<LanguageProvider>(builder: (context, provider, child) {return provider.languageModelObj!.radioList1.isNotEmpty ? Column(children: [CustomRadioButton(width: 380.h, text: "lbl_mandarin".tr, value: provider.languageModelObj?.radioList1[0] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_hindi".tr, value: provider.languageModelObj?.radioList1[1] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_spanish".tr, value: provider.languageModelObj?.radioList1[2] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);})), Padding(padding: EdgeInsets.only(top: 17.v), child: CustomRadioButton(width: 380.h, text: "lbl_french".tr, value: provider.languageModelObj?.radioList1[3] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);})), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_arabic".tr, value: provider.languageModelObj?.radioList1[4] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_bengali".tr, value: provider.languageModelObj?.radioList1[5] ?? "", groupValue: provider.others, isRightCheck: true, onChange: (value) {provider.changeRadioButton2(value);}))]) : Container();}); } 
 }
