import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/layout2_item_model.dart';import '../models/layout4_item_model.dart';import 'package:the_3_17_housit___buyrentsell_property/presentation/form_detail_screen/models/form_detail_model.dart';part 'form_detail_event.dart';part 'form_detail_state.dart';/// A bloc that manages the state of a FormDetail according to the event that is dispatched to it.
class FormDetailBloc extends Bloc<FormDetailEvent, FormDetailState> {FormDetailBloc(FormDetailState initialState) : super(initialState) { on<FormDetailInitialEvent>(_onInitialize); on<UpdateChipViewEvent>(_updateChipView); on<UpdateChipView1Event>(_updateChipView1); }

_updateChipView(UpdateChipViewEvent event, Emitter<FormDetailState> emit, ) { List<Layout2ItemModel> newList = List<Layout2ItemModel>.from(state.formDetailModelObj!.layout2ItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(layout2ItemList: newList))); } 
_updateChipView1(UpdateChipView1Event event, Emitter<FormDetailState> emit, ) { List<Layout4ItemModel> newList = List<Layout4ItemModel>.from(state.formDetailModelObj!.layout4ItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(layout4ItemList: newList))); } 
List<Layout2ItemModel> fillLayout2ItemList() { return List.generate(2, (index) => Layout2ItemModel()); } 
List<Layout4ItemModel> fillLayout4ItemList() { return List.generate(5, (index) => Layout4ItemModel()); } 
_onInitialize(FormDetailInitialEvent event, Emitter<FormDetailState> emit, ) async  { emit(state.copyWith(formPasswordController: TextEditingController())); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(layout2ItemList: fillLayout2ItemList(), layout4ItemList: fillLayout4ItemList()))); } 
 }
