import 'package:flutter/material.dart';import 'package:the_7_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';class LoginScreen extends StatelessWidget {const LoginScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: 355.h, child: Column(children: [SizedBox(height: 416.v, width: 355.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgBackgroundIllustration416x355, height: 416.v, width: 355.h, alignment: Alignment.center), _buildAppBar(context)])), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 14.h), child: Text("Ready to explore? 👋", style: theme.textTheme.headlineSmall))), SizedBox(height: 42.v), CustomElevatedButton(text: "Continue with Email", margin: EdgeInsets.symmetric(horizontal: 14.h), leftIcon: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 20.adaptSize, width: 20.adaptSize)), onPressed: () {onTapContinueWithEmail(context);}), SizedBox(height: 18.v), _buildItemSeparator(context), SizedBox(height: 18.v), _buildGoogle(context)])), bottomNavigationBar: _buildSeventySeven(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 64.v, leadingWidth: 74.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgProfile, margin: EdgeInsets.symmetric(horizontal: 24.h))]); } 
/// Section Widget
Widget _buildItemSeparator(BuildContext context) { return SizedBox(height: 25.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 11.v), child: SizedBox(width: 327.h, child: Divider(color: appTheme.blueGray50)))), CustomElevatedButton(height: 25.v, width: 35.h, text: "OR", buttonStyle: CustomButtonStyles.fillWhiteA1, buttonTextStyle: CustomTextStyles.labelMediumOnPrimaryContainer, alignment: Alignment.center)])); } 
/// Section Widget
Widget _buildGoogle(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 70.v, width: 158.h, padding: EdgeInsets.symmetric(vertical: 22.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 25.adaptSize, width: 25.adaptSize, alignment: Alignment.topCenter)), Container(height: 70.v, width: 158.h, margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(vertical: 22.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 25.adaptSize, width: 25.adaptSize, alignment: Alignment.topCenter))])); } 
/// Section Widget
Widget _buildSeventySeven(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 78.h, right: 78.h, bottom: 24.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("Don’t have an account?", style: theme.textTheme.bodyMedium)), GestureDetector(onTap: () {onTapTxtRegister(context);}, child: Padding(padding: EdgeInsets.only(left: 13.h), child: Text("Register", style: CustomTextStyles.titleSmallPrimaryBold)))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the formEmptyScreen when the action is triggered.
onTapContinueWithEmail(BuildContext context) { Navigator.pushNamed(context, AppRoutes.formEmptyScreen); } 
/// Navigates to the registerFormEmptyScreen when the action is triggered.
onTapTxtRegister(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerFormEmptyScreen); } 
 }
