import 'package:flutter/material.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/custom_elevated_button.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/custom_switch.dart';
// ignore_for_file: must_be_immutable
class ProfileSettingsPage extends StatelessWidget {ProfileSettingsPage({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Row(children: [SizedBox(height: 80.adaptSize, width: 80.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse80x80, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEdit, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.bottomRight)])), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Andrew Ainsley", style: theme.textTheme.titleLarge), SizedBox(height: 8.v), Text("user@domain.com", style: theme.textTheme.titleSmall)]))])), SizedBox(height: 23.v), _buildGetPremium(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedShield: ImageConstant.imgLock, security: "Profile", onTapAutoLayoutHorizontal: () {onTapAutoLayoutHorizontal(context);}), SizedBox(height: 24.v), _buildAutoLayoutHorizontal2(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal3(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal5(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedShield: ImageConstant.imgIconlyCurvedShield, security: "Security", onTapAutoLayoutHorizontal: () {onTapAutoLayoutHorizontal5(context);}), SizedBox(height: 24.v), _buildAutoLayoutHorizontal7(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal8(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgUserRedA200, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Logout", style: CustomTextStyles.titleMediumRedA200))]))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 9.v)), title: AppbarTitle(text: "Profile", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildGetPremium(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 30.v, bottom: 27.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Enjoy All Benefits!", style: CustomTextStyles.headlineSmallWhiteA700), SizedBox(height: 8.v), SizedBox(width: 202.h, child: Text("Enjoy listening songs & podcasts with better audio quality, without restrictions, and without ads.", maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall)), SizedBox(height: 11.v), CustomElevatedButton(height: 32.v, width: 116.h, text: "Get Premium", buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer, onPressed: () {onTapGetPremium(context);})])), CustomImageView(imagePath: ImageConstant.imgMusicFococlippingStandard, height: 169.v, width: 115.h, margin: EdgeInsets.only(top: 13.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal2(BuildContext context) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal1(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 144.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconsGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("Notification", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3(BuildContext context) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal2(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMenu, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("Audio & Video", style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal3(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 124.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedPlay, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("Playback", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal5(BuildContext context) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal4(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Data Saver & Storage", style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal7(BuildContext context) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal6(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedMore, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Language", style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("English (US)", style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal8(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEyeGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("Dark Mode", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomSwitch(value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})]); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String iconlyCurvedShield, required String security, Function? onTapAutoLayoutHorizontal, }) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: iconlyCurvedShield, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text(security, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Navigates to the subscribeScreen when the action is triggered.
onTapGetPremium(BuildContext context) { Navigator.pushNamed(context, AppRoutes.subscribeScreen); } 
/// Navigates to the profileDetailsOneScreen when the action is triggered.
onTapAutoLayoutHorizontal(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profileDetailsOneScreen); } 
/// Navigates to the notificationSettingsScreen when the action is triggered.
onTapAutoLayoutHorizontal1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.notificationSettingsScreen); } 
/// Navigates to the audioVideoScreen when the action is triggered.
onTapAutoLayoutHorizontal2(BuildContext context) { Navigator.pushNamed(context, AppRoutes.audioVideoScreen); } 
/// Navigates to the playbackScreen when the action is triggered.
onTapAutoLayoutHorizontal3(BuildContext context) { Navigator.pushNamed(context, AppRoutes.playbackScreen); } 
/// Navigates to the dataSaverStorageScreen when the action is triggered.
onTapAutoLayoutHorizontal4(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dataSaverStorageScreen); } 
/// Navigates to the securityScreen when the action is triggered.
onTapAutoLayoutHorizontal5(BuildContext context) { Navigator.pushNamed(context, AppRoutes.securityScreen); } 
/// Navigates to the languageScreen when the action is triggered.
onTapAutoLayoutHorizontal6(BuildContext context) { Navigator.pushNamed(context, AppRoutes.languageScreen); } 
 }
