import 'notifier/notification_settings_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_07_comfort___hotel_booking_app/core/app_export.dart';import 'package:the_6_07_comfort___hotel_booking_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_07_comfort___hotel_booking_app/widgets/app_bar/appbar_title.dart';import 'package:the_6_07_comfort___hotel_booking_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_6_07_comfort___hotel_booking_app/widgets/custom_switch.dart';class NotificationSettingsScreen extends ConsumerStatefulWidget {const NotificationSettingsScreen({Key? key}) : super(key: key);

@override NotificationSettingsScreenState createState() =>  NotificationSettingsScreenState();

 }
class NotificationSettingsScreenState extends ConsumerState<NotificationSettingsScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Column(children: [_buildAutoLayoutHorizontal(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal2(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal3(context), SizedBox(height: 30.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal5(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_notifications".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("msg_general_notification".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox1(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_sound".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch1, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox2(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_vibrate".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch2, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox3(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_app_updates".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch3, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox4(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("msg_new_service_available".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch4, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox5(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal5(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_new_tips_available".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Consumer(builder: (context, ref, _) {return CustomSwitch(value: ref.watch(notificationSettingsNotifier).isSelectedSwitch5, onChange: (value) {ref.read(notificationSettingsNotifier.notifier).changeSwitchBox6(value);});})]); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
