import 'bloc/empty_search_bloc.dart';import 'models/empty_search_model.dart';import 'package:flutter/material.dart';import 'package:the_3_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_3_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_3_17_housit___buyrentsell_property/widgets/app_bar/appbar_subtitle.dart';import 'package:the_3_17_housit___buyrentsell_property/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:the_3_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_17_housit___buyrentsell_property/widgets/custom_search_view.dart';import 'package:the_3_17_housit___buyrentsell_property/presentation/filter_full_bottomsheet/filter_full_bottomsheet.dart';class EmptySearchScreen extends StatelessWidget {const EmptySearchScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EmptySearchBloc>(create: (context) => EmptySearchBloc(EmptySearchState(emptySearchModelObj: EmptySearchModel()))..add(EmptySearchInitialEvent()), child: EmptySearchScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 17.v), child: Column(children: [BlocSelector<EmptySearchBloc, EmptySearchState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_minix".tr);}), SizedBox(height: 20.v), _buildItemHeader(context), Spacer(flex: 39), Container(margin: EdgeInsets.symmetric(horizontal: 92.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.circleBorder71), child: Container(padding: EdgeInsets.all(20.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.circleBorder55), child: Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 19.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.circleBorder35), child: Text("lbl2".tr, style: CustomTextStyles.headlineSmallMontserratWhiteA700)))), SizedBox(height: 15.v), Text("msg_search_not_found".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 31.v), Container(width: 279.h, margin: EdgeInsets.only(left: 24.h, right: 23.h), child: Text("msg_sorry_we_can_t".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.50))), Spacer(flex: 60)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_search_results".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgIconSetting, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 3.v), onTap: () {onTapIconSetting(context);})]); } 
/// Section Widget
Widget _buildItemHeader(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 9.v, bottom: 8.v), child: Text("lbl_found".tr, style: CustomTextStyles.titleMediumMedium)), Padding(padding: EdgeInsets.only(left: 5.h, top: 10.v, bottom: 7.v), child: Text("lbl_0".tr, style: CustomTextStyles.titleMediumRedA200)), Padding(padding: EdgeInsets.only(left: 5.h, top: 9.v, bottom: 8.v), child: Text("lbl_estates".tr, style: CustomTextStyles.titleMediumMedium)), Spacer(), Container(width: 93.h, padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Container(height: 24.v, width: 36.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomImageView(imagePath: ImageConstant.imgGridOnprimarycontainer, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center)), Container(height: 24.v, width: 36.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomImageView(imagePath: ImageConstant.imgIconHorizontalBlueGray8000112x12, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center))]))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 

/// Displays a bottom sheet widget using the [showModalBottomSheet] method 
/// of the [Scaffold] class with [isScrollControlled] set to true.
///
/// The bottom sheet is built using the [FilterFullBottomsheet]
/// class and the [builder] method of the bottom sheet is passed the
/// [BuildContext] object.
onTapIconSetting(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>FilterFullBottomsheet.builder(context),isScrollControlled: true); } 
 }
