import 'package:flutter/material.dart';import 'package:the_7_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_icon_button.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class ReviewSelectVoucherBottomsheet extends StatelessWidget {ReviewSelectVoucherBottomsheet({Key? key}) : super(key: key);

TextEditingController televisionController = TextEditingController();

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.customBorderTL50), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), SizedBox(width: 60.h, child: Divider()), SizedBox(height: 36.v), Align(alignment: Alignment.centerLeft, child: Text("Add Voucher", style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), CustomTextFormField(controller: televisionController, hintText: "Type your voucher ", hintStyle: CustomTextStyles.bodyMediumOnPrimaryContainer, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 25.v, 10.h, 24.v), child: CustomImageView(imagePath: ImageConstant.imgTelevisionBlueGray80001, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.only(top: 26.v, right: 30.h, bottom: 26.v)), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Text("Your Available vouchers", style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), _buildCardCoupon(context), SizedBox(height: 10.v), _buildCardCoupon(context), SizedBox(height: 13.v), CustomElevatedButton(text: "Apply Voucher", onPressed: () {onTapApplyVoucher(context);})])); } 
/// Common widget
Widget _buildCardCoupon(BuildContext context) { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.gradientGreenAToTealA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(children: [CustomIconButton(height: 53.adaptSize, width: 53.adaptSize, padding: EdgeInsets.all(14.h), decoration: IconButtonStyleHelper.fillGreenA, child: CustomImageView(imagePath: ImageConstant.imgTelevisionWhiteA70053x53)), Padding(padding: EdgeInsets.only(left: 16.h, top: 6.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("HGJC20", style: CustomTextStyles.titleMediumBold), SizedBox(height: 7.v), Text("Click to use this voucher", style: theme.textTheme.labelSmall)]))])); } 
/// Navigates to the reviewFillScreen when the action is triggered.
onTapApplyVoucher(BuildContext context) { Navigator.pushNamed(context, AppRoutes.reviewFillScreen); } 
 }
