import 'package:flutter/material.dart';import 'package:the_7_21_vertex___real_estate_app/core/app_export.dart';import 'package:the_7_21_vertex___real_estate_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_7_21_vertex___real_estate_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:the_7_21_vertex___real_estate_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_21_vertex___real_estate_app/widgets/custom_icon_button.dart';class ProfilePage extends StatelessWidget {const ProfilePage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [SizedBox(height: 70.adaptSize, width: 70.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgRectangle361, height: 70.adaptSize, width: 70.adaptSize, radius: BorderRadius.circular(35.h), alignment: Alignment.center), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.outlineGrayTL12, alignment: Alignment.bottomRight, onTap: () {onTapBtnTelevision(context);}, child: CustomImageView(imagePath: ImageConstant.imgTelevisionGray50))])), SizedBox(height: 8.v), Text("Cameron Williamson", style: CustomTextStyles.titleMediumBold_1), SizedBox(height: 4.v), Text("hello@gmail.com", style: CustomTextStyles.titleSmallBluegray500Medium), SizedBox(height: 31.v), _buildGeneral(context, general: "Home search", sellMyHome: "Recently viewed", myListings: "My favorites", settings: "Past Tour", onTapSellMyHome: () {onTapRecentltyViewed(context);}, onTapMyListings: () {onTapMyFavorites(context);}, onTapSettings: () {onTapPastTour(context);}), SizedBox(height: 32.v), _buildGeneral(context, general: "General", sellMyHome: "Sell my home", myListings: "My listings ", settings: "Settings", onTapMyListings: () {onTapMyListings(context);}, onTapSettings: () {onTapSettings(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "Profile"), styleType: Style.bgFill); } 
/// Common widget
Widget _buildGeneral(BuildContext context, {required String general, required String sellMyHome, required String myListings, required String settings, Function? onTapSellMyHome, Function? onTapMyListings, Function? onTapSettings, }) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text(general, style: CustomTextStyles.titleSmallBluegray500ExtraBold.copyWith(color: appTheme.blueGray500))), SizedBox(height: 16.v), GestureDetector(onTap: () {onTapSellMyHome!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgUserPrimary40x40)), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 7.v), child: Text(sellMyHome, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))])), SizedBox(height: 16.v), GestureDetector(onTap: () {onTapMyListings!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgHomePrimary)), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 7.v), child: Text(myListings, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))])), SizedBox(height: 16.v), GestureDetector(onTap: () {onTapSettings!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgSearch)), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 7.v), child: Text(settings, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))]))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the editProfileScreen when the action is triggered.
onTapBtnTelevision(BuildContext context) { Navigator.pushNamed(context, AppRoutes.editProfileScreen); } 
/// Navigates to the recentlyViewsScreen when the action is triggered.
onTapRecentltyViewed(BuildContext context) { Navigator.pushNamed(context, AppRoutes.recentlyViewsScreen); } 
/// Navigates to the favoriteScreen when the action is triggered.
onTapMyFavorites(BuildContext context) { Navigator.pushNamed(context, AppRoutes.favoriteScreen); } 
/// Navigates to the pastToursScreen when the action is triggered.
onTapPastTour(BuildContext context) { Navigator.pushNamed(context, AppRoutes.pastToursScreen); } 
/// Navigates to the homeListingScreen when the action is triggered.
onTapMyListings(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeListingScreen); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapSettings(BuildContext context) { Navigator.pushNamed(context, AppRoutes.settingsScreen); } 
 }
