import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_pin_code_text_field.dart';class ForgotPasswordTypeOtpScreen extends StatelessWidget {const ForgotPasswordTypeOtpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 118.v, right: 24.h), child: Column(children: [Text("Code has been send to +1 111 ******99", style: CustomTextStyles.titleMediumMedium), SizedBox(height: 61.v), Padding(padding: EdgeInsets.only(right: 1.h), child: CustomPinCodeTextField(context: context, onChanged: (value) {})), SizedBox(height: 60.v), RichText(text: TextSpan(children: [TextSpan(text: "Resend code in ", style: CustomTextStyles.titleMediumMedium_1), TextSpan(text: "55", style: CustomTextStyles.titleMediumPrimaryMedium), TextSpan(text: " s", style: CustomTextStyles.titleMediumMedium_1)]), textAlign: TextAlign.left), SizedBox(height: 98.v), CustomElevatedButton(text: "Verify", buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Forgot Password", margin: EdgeInsets.only(left: 16.h))); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
 }
