import 'models/select_date_guest_model.dart';import 'package:flutter/material.dart';import 'package:table_calendar/table_calendar.dart';import 'package:the_5_07_comfort___hotel_booking_app/core/app_export.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/custom_elevated_button.dart';import 'provider/select_date_guest_provider.dart';class SelectDateGuestScreen extends StatefulWidget {const SelectDateGuestScreen({Key? key}) : super(key: key);

@override SelectDateGuestScreenState createState() =>  SelectDateGuestScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SelectDateGuestProvider(), child: SelectDateGuestScreen()); } 
 }
class SelectDateGuestScreenState extends State<SelectDateGuestScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(children: [SizedBox(height: 7.v), _buildDateCalendar(context), SizedBox(height: 20.v), _buildBookingDetails(context), SizedBox(height: 22.v), Text("lbl_total_435".tr, style: theme.textTheme.titleMedium)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_select_date".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildDateCalendar(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 72.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Consumer<SelectDateGuestProvider>(builder: (context, provider, child) {return SizedBox(height: 251.v, width: 334.h, child: TableCalendar(locale: 'en_US', firstDay: DateTime(DateTime.now().year - 5), lastDay: DateTime(DateTime.now().year + 5), calendarFormat: CalendarFormat.month, rangeSelectionMode: provider.rangeSelectionMode, startingDayOfWeek: StartingDayOfWeek.sunday, headerStyle: HeaderStyle(formatButtonVisible: false, titleCentered: true), calendarStyle: CalendarStyle(outsideDaysVisible: false, isTodayHighlighted: true), daysOfWeekStyle: DaysOfWeekStyle(), headerVisible: false, focusedDay: provider.focusedDay ?? DateTime.now(), rangeStartDay: provider.rangeStart, rangeEndDay: provider.rangeEnd, onDaySelected: (selectedDay, focusedDay) {if (!isSameDay(selectedDay, selectedDay)) {provider.focusedDay = focusedDay; provider.selectedDay = selectedDay; provider.rangeSelectionMode = RangeSelectionMode.toggledOn;}}, onRangeSelected: (start, end, focusedDay) {provider.focusedDay = focusedDay; provider.rangeEnd = end; provider.rangeStart = start; provider.rangeSelectionMode = RangeSelectionMode.toggledOn;}, onPageChanged: (focusedDay) {provider.focusedDay = focusedDay;}));})); } 
/// Section Widget
Widget _buildBookingDetails(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 78.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_check_in".tr, style: theme.textTheme.titleMedium), Text("lbl_check_out".tr, style: theme.textTheme.titleMedium)])), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildCheckOut(context, decCounter: "lbl_dec_16".tr), CustomImageView(imagePath: ImageConstant.imgFavoriteWhiteA700, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 18.v)), _buildCheckOut(context, decCounter: "lbl_dec_20".tr)]), SizedBox(height: 30.v), Text("lbl_guest".tr, style: theme.textTheme.titleMedium), SizedBox(height: 15.v), Container(padding: EdgeInsets.symmetric(horizontal: 82.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(16.h), decoration: AppDecoration.outlineIndigoA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomImageView(imagePath: ImageConstant.imgFrameWhiteA70020x20, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 12.v), child: Text("lbl_3".tr, style: theme.textTheme.headlineSmall)), Container(height: 52.adaptSize, width: 52.adaptSize, padding: EdgeInsets.all(16.h), decoration: AppDecoration.outlineIndigoA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomImageView(imagePath: ImageConstant.imgFrame20x20, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.center))]))]); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 33.v), onPressed: () {onTapContinue(context);}); } 
/// Common widget
Widget _buildCheckOut(BuildContext context, {required String decCounter, }) { return Container(width: 160.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Text(decCounter, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.whiteA700))), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedCalendarPrimary, height: 20.adaptSize, width: 20.adaptSize)])); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the bookingNameTabContainerScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.bookingNameTabContainerScreen, ); } 
 }
