import '../review_empty_screen/widgets/cardlist_item_widget.dart';import 'controller/review_empty_controller.dart';import 'models/cardlist_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_subtitle.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_icon_button.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_text_form_field.dart';import 'package:the_4_17_housit___buyrentsell_property/presentation/review_select_voucher_bottomsheet/review_select_voucher_bottomsheet.dart';import 'package:the_4_17_housit___buyrentsell_property/presentation/review_select_voucher_bottomsheet/controller/review_select_voucher_controller.dart';class ReviewEmptyScreen extends GetWidget<ReviewEmptyController> {const ReviewEmptyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 17.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildEstatesCardTransaction(), SizedBox(height: 37.v), _buildPeriod(), SizedBox(height: 37.v), _buildNote(), SizedBox(height: 39.v), Text("lbl_payment_method".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), _buildCardList(), SizedBox(height: 37.v), _buildItemHeader(), SizedBox(height: 55.v), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 1.v, width: 100.h, margin: EdgeInsets.only(left: 114.h))]))))])), bottomNavigationBar: _buildNext())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "msg_transaction_review".tr)); } 
/// Section Widget
Widget _buildEstatesCardTransaction() { return Container(margin: EdgeInsets.only(right: 24.h), padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 140.v, width: 168.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgShape20, height: 140.v, width: 168.h, radius: BorderRadius.circular(18.h), alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillWhiteATL121, child: CustomImageView(imagePath: ImageConstant.imgFavoriteRedA200)), SizedBox(height: 75.v), CustomElevatedButton(height: 24.v, width: 72.h, text: "lbl_apartment".tr, leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 13.v, width: 11.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAfTL8, buttonTextStyle: CustomTextStyles.labelSmallGray100)])))])), Padding(padding: EdgeInsets.fromLTRB(16.h, 52.v, 9.h, 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 12.adaptSize, width: 12.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_jakarta_indonesia".tr, style: theme.textTheme.labelSmall))]), SizedBox(height: 18.v), CustomElevatedButton(height: 50.v, width: 94.h, text: "lbl_rent".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.fillWhiteATL25, buttonTextStyle: theme.textTheme.labelMedium!, alignment: Alignment.centerRight)]))])); } 
/// Section Widget
Widget _buildPeriod() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_period".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 23.h), child: Row(children: [CustomTextFormField(width: 158.h, controller: controller.formDateEmptyController, hintText: "lbl_check_in".tr, hintStyle: CustomTextStyles.labelLargeOnPrimaryContainer, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 25.v, 10.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.only(top: 27.v, right: 30.h, bottom: 27.v)), Padding(padding: EdgeInsets.only(left: 11.h), child: CustomTextFormField(width: 158.h, controller: controller.formDateEmptyController1, hintText: "lbl_check_out".tr, hintStyle: CustomTextStyles.labelLargeOnPrimaryContainer, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 25.v, 10.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.only(top: 27.v, right: 30.h, bottom: 27.v)))]))]); } 
/// Section Widget
Widget _buildNote() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_note_for_owner".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 24.h), child: CustomTextFormField(controller: controller.televisionController, hintText: "msg_write_your_note".tr, hintStyle: CustomTextStyles.bodyMediumOnPrimaryContainer, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 25.v, 10.h, 24.v), child: CustomImageView(imagePath: ImageConstant.imgTelevision, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.only(top: 26.v, right: 30.h, bottom: 26.v)))]); } 
/// Section Widget
Widget _buildCardList() { return SizedBox(height: 180.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: controller.reviewEmptyModelObj.value.cardlistItemList.value.length, itemBuilder: (context, index) {CardlistItemModel model = controller.reviewEmptyModelObj.value.cardlistItemList.value[index]; return CardlistItemWidget(model);}))); } 
/// Section Widget
Widget _buildItemHeader() { return Padding(padding: EdgeInsets.only(right: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_have_a_voucher".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: Text("lbl_click_in_here".tr, style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildNext() { return CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), onPressed: () {onTapNext();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [ReviewSelectVoucherBottomsheet] widget.
///
/// The bottom sheet is controlled by the [ReviewSelectVoucherController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapNext() { Get.bottomSheet(ReviewSelectVoucherBottomsheet(Get.put(ReviewSelectVoucherController(),),),isScrollControlled: true,); } 
 }
