import '../podcasts_screen/widgets/artists_item_widget.dart';import '../podcasts_screen/widgets/frame_item_widget.dart';import '../podcasts_screen/widgets/podcasts_item_widget.dart';import 'controller/podcasts_controller.dart';import 'models/artists_item_model.dart';import 'models/frame_item_model.dart';import 'models/podcasts_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';class PodcastsScreen extends GetWidget<PodcastsController> {const PodcastsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 32.v), child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 24.h), child: _buildAutoLayoutHorizontal(popularArtists: "msg_popular_podcasts".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildFrame(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(right: 24.h), child: _buildAutoLayoutHorizontal(popularArtists: "lbl_popular_artists".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildArtists(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(right: 24.h), child: _buildAutoLayoutHorizontal(popularArtists: "lbl_categories".tr, seeAll: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildPodcasts()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_podcasts".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 10.h)), AppbarTrailingImage(imagePath: ImageConstant.imgTelevision, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 10.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 34.h))]); } 
/// Section Widget
Widget _buildFrame() { return SizedBox(height: 220.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.podcastsModelObj.value.frameItemList.value.length, itemBuilder: (context, index) {FrameItemModel model = controller.podcastsModelObj.value.frameItemList.value[index]; return FrameItemWidget(model);}))); } 
/// Section Widget
Widget _buildArtists() { return SizedBox(height: 209.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.podcastsModelObj.value.artistsItemList.value.length, itemBuilder: (context, index) {ArtistsItemModel model = controller.podcastsModelObj.value.artistsItemList.value[index]; return ArtistsItemWidget(model);}))); } 
/// Section Widget
Widget _buildPodcasts() { return Padding(padding: EdgeInsets.only(right: 24.h), child: Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 121.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.podcastsModelObj.value.podcastsItemList.value.length, itemBuilder: (context, index) {PodcastsItemModel model = controller.podcastsModelObj.value.podcastsItemList.value[index]; return PodcastsItemWidget(model, onTapExploreCard: () {onTapExploreCard();});}))); } 
/// Common widget
Widget _buildAutoLayoutHorizontal({required String popularArtists, required String seeAll, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(popularArtists, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001))), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text(seeAll, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer)))]); } 
/// Navigates to the newReleasesScreen when the action is triggered.
onTapExploreCard() { Get.toNamed(AppRoutes.newReleasesScreen); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
