import '../trending_sounds_details_screen/widgets/autolayoutvertical3_item_widget.dart';import 'models/autolayoutvertical3_item_model.dart';import 'notifier/trending_sounds_details_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/custom_outlined_button.dart';class TrendingSoundsDetailsScreen extends ConsumerStatefulWidget {const TrendingSoundsDetailsScreen({Key? key}) : super(key: key);

@override TrendingSoundsDetailsScreenState createState() =>  TrendingSoundsDetailsScreenState();

 }
class TrendingSoundsDetailsScreenState extends ConsumerState<TrendingSoundsDetailsScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 28.v), child: Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 52.h), child: Row(children: [SizedBox(height: 140.adaptSize, width: 140.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage140x140, height: 140.adaptSize, width: 140.adaptSize, radius: BorderRadius.circular(24.h), alignment: Alignment.center), CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(2.h), decoration: IconButtonStyleHelper.radiusTL16, alignment: Alignment.center, child: CustomImageView(imagePath: ImageConstant.imgOverflowMenuOnerrorcontainer))])), Padding(padding: EdgeInsets.only(left: 22.h, top: 15.v, bottom: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 165.h, child: Text("msg_favorite_girl_by".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.20))), SizedBox(height: 31.v), Text("lbl_387_5m_videos".tr, style: theme.textTheme.titleSmall)]))]))), SizedBox(height: 24.v), _buildPlaySong(context), SizedBox(height: 26.v), _buildFollow(context), SizedBox(height: 26.v), Divider(), SizedBox(height: 37.v), _buildAutoLayoutVertical(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_trending_sounds".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCategoriesShareGray900, margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 13.v))]); } 
/// Section Widget
Widget _buildPlaySong(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(height: 36.v, text: "lbl_play_song".tr, margin: EdgeInsets.only(right: 4.h), leftIcon: Container(margin: EdgeInsets.only(right: 4.h), child: CustomImageView(imagePath: ImageConstant.imgOverflowmenuPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonTextStyle: CustomTextStyles.titleSmallPrimaryBold)), Expanded(child: CustomOutlinedButton(height: 36.v, text: "msg_add_to_favorites".tr, margin: EdgeInsets.only(left: 4.h), leftIcon: Container(margin: EdgeInsets.only(right: 3.h), child: CustomImageView(imagePath: ImageConstant.imgBookmarkPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonTextStyle: CustomTextStyles.titleSmallPrimaryBold))]); } 
/// Section Widget
Widget _buildFollow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 188.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEllipse19, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_justin_bieber".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Text("msg_professional_singer".tr, style: theme.textTheme.titleSmall)]))])), CustomElevatedButton(height: 32.v, width: 73.h, text: "lbl_follow".tr, margin: EdgeInsets.symmetric(vertical: 14.v))]); } 
/// Section Widget
Widget _buildAutoLayoutVertical(BuildContext context) { return Consumer(builder: (context, ref, _) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 409.v, crossAxisCount: 2, mainAxisSpacing: 6.h, crossAxisSpacing: 6.h), physics: NeverScrollableScrollPhysics(), itemCount: ref.watch(trendingSoundsDetailsNotifier).trendingSoundsDetailsModelObj?.autolayoutvertical3ItemList.length ?? 0, itemBuilder: (context, index) {Autolayoutvertical3ItemModel model = ref.watch(trendingSoundsDetailsNotifier).trendingSoundsDetailsModelObj?.autolayoutvertical3ItemList[index] ?? Autolayoutvertical3ItemModel(); return Autolayoutvertical3ItemWidget(model);});}); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
