import '../podcast_details_screen/widgets/podcastdetails_item_widget.dart';import 'package:flutter/material.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/custom_elevated_button.dart';class PodcastDetailsScreen extends StatelessWidget {const PodcastDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse250x250, height: 250.adaptSize, width: 250.adaptSize, radius: BorderRadius.circular(125.h)), SizedBox(height: 14.v), Text("Ariana Grande", style: theme.textTheme.headlineLarge), SizedBox(height: 15.v), Text("55,278,829 monthly listeners", style: CustomTextStyles.titleMediumPrimaryMedium_1), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 111.h), child: Row(children: [CustomElevatedButton(height: 45.v, width: 101.h, text: "Follow", buttonStyle: CustomButtonStyles.fillPrimaryTL22, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1, onPressed: () {onTapFollow(context);}), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgIconsGray90001, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgCategoriesShare, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))]))), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: GestureDetector(onTap: () {onTapTxtLoremipsumdolor(context);}, child: Container(width: 366.h, margin: EdgeInsets.only(right: 13.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad, ", style: CustomTextStyles.titleMediumPrimaryMedium), TextSpan(text: "view more...", style: CustomTextStyles.titleMediumOnPrimaryContainerMedium16)]), textAlign: TextAlign.left)))), SizedBox(height: 21.v), Divider(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 21.v), _buildPodcastDetails(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Episodes", style: theme.textTheme.headlineSmall)), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text("See All", style: CustomTextStyles.titleMediumOnPrimaryContainer16))]); } 
/// Section Widget
Widget _buildPodcastDetails(BuildContext context) { return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: 2, itemBuilder: (context, index) {return PodcastdetailsItemWidget();}); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapFollow(BuildContext context) { Navigator.pushNamed(context, AppRoutes.songPlayScreen); } 
/// Navigates to the podcastEpisodeDetailsScreen when the action is triggered.
onTapTxtLoremipsumdolor(BuildContext context) { Navigator.pushNamed(context, AppRoutes.podcastEpisodeDetailsScreen); } 
 }
