import '../extra_information_screen/widgets/layout11_item_widget.dart';import '../extra_information_screen/widgets/layout6_item_widget.dart';import '../extra_information_screen/widgets/layout8_item_widget.dart';import '../extra_information_screen/widgets/layout9_item_widget.dart';import 'models/layout11_item_model.dart';import 'models/layout6_item_model.dart';import 'models/layout8_item_model.dart';import 'models/layout9_item_model.dart';import 'notifier/extra_information_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_6_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_6_17_housit___buyrentsell_property/widgets/app_bar/appbar_subtitle.dart';import 'package:the_6_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_6_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_6_17_housit___buyrentsell_property/widgets/custom_text_form_field.dart';import 'package:the_6_17_housit___buyrentsell_property/presentation/extra_information_success_bottomsheet/extra_information_success_bottomsheet.dart';class ExtraInformationScreen extends ConsumerStatefulWidget {const ExtraInformationScreen({Key? key}) : super(key: key);

@override ExtraInformationScreenState createState() =>  ExtraInformationScreenState();

 }
class ExtraInformationScreenState extends ConsumerState<ExtraInformationScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 49.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 3.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 267.h, margin: EdgeInsets.only(right: 81.h), child: Text("msg_almost_finish_complete_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50)))), SizedBox(height: 43.v), _buildSellPrice(context), SizedBox(height: 37.v), _buildRentPrice(context), SizedBox(height: 38.v), _buildPropertyFeatures(context), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_total_rooms".tr, style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), _buildLayout(context), SizedBox(height: 36.v), _buildEnvironment(context), SizedBox(height: 46.v), CustomImageView(imagePath: ImageConstant.imgProgressBarGradient, height: 1.v, width: 100.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 114.h))]))))])), bottomNavigationBar: _buildFinish(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_listing".tr)); } 
/// Section Widget
Widget _buildSellPrice(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sell_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 27.h), child: Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(extraInformationNotifier).priceController, hintText: "lbl_180_000".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v));}))]); } 
/// Section Widget
Widget _buildRentPrice(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_rent_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 24.h), child: Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(extraInformationNotifier).priceController1, hintText: "lbl_315".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v));})), SizedBox(height: 15.v), Consumer(builder: (context, ref, _) {return Wrap(runSpacing: 3.v, spacing: 3.h, children: List<Widget>.generate(ref.watch(extraInformationNotifier).extraInformationModelObj?.layout6ItemList.length ?? 0, (index) {Layout6ItemModel model = ref.watch(extraInformationNotifier).extraInformationModelObj?.layout6ItemList[index] ?? Layout6ItemModel(); return Layout6ItemWidget(model, onSelectedChipView1: (value) {ref.read(extraInformationNotifier.notifier).onSelectedChipView1(index, value);});}));})]); } 
/// Section Widget
Widget _buildPropertyFeatures(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_property_features".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(right: 21.h), child: Consumer(builder: (context, ref, _) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: ref.watch(extraInformationNotifier).extraInformationModelObj?.layout8ItemList.length ?? 0, itemBuilder: (context, index) {Layout8ItemModel model = ref.watch(extraInformationNotifier).extraInformationModelObj?.layout8ItemList[index] ?? Layout8ItemModel(); return Layout8ItemWidget(model);});}))]); } 
/// Section Widget
Widget _buildLayout(BuildContext context) { return Consumer(builder: (context, ref, _) {return Wrap(runSpacing: 10.v, spacing: 10.h, children: List<Widget>.generate(ref.watch(extraInformationNotifier).extraInformationModelObj?.layout9ItemList.length ?? 0, (index) {Layout9ItemModel model = ref.watch(extraInformationNotifier).extraInformationModelObj?.layout9ItemList[index] ?? Layout9ItemModel(); return Layout9ItemWidget(model, onSelectedChipView2: (value) {ref.read(extraInformationNotifier.notifier).onSelectedChipView2(index, value);});}));}); } 
/// Section Widget
Widget _buildEnvironment(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_environment_facilities".tr, style: CustomTextStyles.titleMediumBold), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return Wrap(runSpacing: 4.v, spacing: 4.h, children: List<Widget>.generate(ref.watch(extraInformationNotifier).extraInformationModelObj?.layout11ItemList.length ?? 0, (index) {Layout11ItemModel model = ref.watch(extraInformationNotifier).extraInformationModelObj?.layout11ItemList[index] ?? Layout11ItemModel(); return Layout11ItemWidget(model, onSelectedChipView3: (value) {ref.read(extraInformationNotifier.notifier).onSelectedChipView3(index, value);});}));})])); } 
/// Section Widget
Widget _buildFinish(BuildContext context) { return CustomElevatedButton(text: "lbl_finish".tr, margin: EdgeInsets.only(left: 25.h, right: 23.h, bottom: 24.v), onPressed: () {onTapFinish(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 

/// Shows a modal bottom sheet with [ExtraInformationSuccessBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapFinish(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>ExtraInformationSuccessBottomsheet(),isScrollControlled: true); } 
 }
