import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';class LogoutModalBottomsheet extends StatelessWidget {const LogoutModalBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return _buildAutoLayoutVertical(context); } 
/// Section Widget
Widget _buildCancel(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgFrameGray300, height: 3.v, width: 38.h), SizedBox(height: 27.v), Text("Logout", style: CustomTextStyles.headlineSmallRedA200), SizedBox(height: 46.v), Text("Are you sure you want to log out?", style: CustomTextStyles.titleLargeErrorContainer), SizedBox(height: 22.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(width: 166.h, text: "Cancel", buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary, onPressed: () {onTapCancel(context);}), CustomElevatedButton(width: 166.h, text: "Yes, Log Out", margin: EdgeInsets.only(left: 24.h), buttonStyle: CustomButtonStyles.fillSecondaryContainer, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16)])]))); } 
/// Section Widget
Widget _buildAutoLayoutVertical(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.onErrorContainer, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.gray100, width: 1.h), borderRadius: BorderRadiusStyle.customBorderTL40), child: Container(height: 266.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 7.v), decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 80.v), child: SizedBox(width: 380.h, child: Divider()))), _buildCancel(context)]))); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapCancel(BuildContext context) { Navigator.pushNamed(context, AppRoutes.settingsScreen); } 
 }
