import 'controller/language_controller.dart';import 'package:flutter/material.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_radio_button.dart';class LanguageScreen extends GetWidget<LanguageController> {const LanguageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(height: 829.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 21.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 158.v), child: SizedBox(width: 380.h, child: Divider()))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_suggested".tr, style: theme.textTheme.titleLarge), SizedBox(height: 31.v), _buildGroup386(), SizedBox(height: 66.v), Text("lbl_language".tr, style: theme.textTheme.titleLarge), SizedBox(height: 21.v), _buildLanguage()])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_language".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildGroup386() { return Obx(() => Column(children: [CustomRadioButton(width: 382.h, text: "lbl_english_us".tr, value: controller.languageModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.radioGroup.value = value;}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_english_uk".tr, value: controller.languageModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.radioGroup.value = value;}))])); } 
/// Section Widget
Widget _buildLanguage() { return Obx(() => Column(children: [CustomRadioButton(width: 382.h, text: "lbl_mandarin".tr, value: controller.languageModelObj.value.radioList1.value[0], groupValue: controller.language.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_hindi".tr, value: controller.languageModelObj.value.radioList1.value[1], groupValue: controller.language.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_spanish".tr, value: controller.languageModelObj.value.radioList1.value[2], groupValue: controller.language.value, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "lbl_french".tr, value: controller.languageModelObj.value.radioList1.value[3], groupValue: controller.language.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_arabic".tr, value: controller.languageModelObj.value.radioList1.value[4], groupValue: controller.language.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_bengali".tr, value: controller.languageModelObj.value.radioList1.value[5], groupValue: controller.language.value, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "lbl_russian".tr, value: controller.languageModelObj.value.radioList1.value[6], groupValue: controller.language.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {controller.language.value = value;}))])); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
