import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_radio_button.dart';
// ignore_for_file: must_be_immutable
class ReportScreen extends StatelessWidget {ReportScreen({Key? key}) : super(key: key);

String selectAReason = "";

List<String> radioList = ["msg_violent_graphic", "lbl_animal_cruelty", "msg_pornography_nudity", "lbl_hate_speech", "msg_harassment_or_bullying", "msg_intellectual_property", "lbl_spam", "lbl_minor_safety", "lbl_other"];

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Select a reason", style: CustomTextStyles.titleMediumMedium), SizedBox(height: 25.v), _buildSelectAReason(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAutoLayoutHorizontal(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Report", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSelectAReason(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 71.h), child: Column(children: [Padding(padding: EdgeInsets.only(right: 59.h), child: CustomRadioButton(text: "Violent & graphic contents", value: radioList[0], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 152.h), child: CustomRadioButton(text: "Animal Cruelty", value: radioList[1], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 96.h), child: CustomRadioButton(text: "Pornography & nudity", value: radioList[2], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 168.h), child: CustomRadioButton(text: "Hate Speech", value: radioList[3], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 87.h), child: CustomRadioButton(text: "Harassment or bullying", value: radioList[4], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(text: "Intellectual property infringement", value: radioList[5], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 224.h), child: CustomRadioButton(text: "Spam", value: radioList[6], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 20.v, right: 167.h), child: CustomRadioButton(text: "Minor Safety", value: radioList[7], groupValue: selectAReason, onChange: (value) {selectAReason = value;})), Padding(padding: EdgeInsets.only(top: 21.v, right: 225.h), child: CustomRadioButton(text: "Other", value: radioList[8], groupValue: selectAReason, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {selectAReason = value;}))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(width: 184.h, text: "Cancel", buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary), CustomElevatedButton(width: 184.h, text: "Submit", margin: EdgeInsets.only(left: 12.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16)])); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
 }
