import 'package:flutter/material.dart';import 'package:the_7_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_7_17_housit___buyrentsell_property/presentation/payment_empty_page/payment_empty_page.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_trailing_button.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';class PaymentEmptyTabContainerScreen extends StatefulWidget {const PaymentEmptyTabContainerScreen({Key? key}) : super(key: key);

@override PaymentEmptyTabContainerScreenState createState() =>  PaymentEmptyTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class PaymentEmptyTabContainerScreenState extends State<PaymentEmptyTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 50.v), Container(width: 226.h, margin: EdgeInsets.only(left: 24.h), child: Text("Add your \npayment method 💸", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("You can edit this later on your account setting.", style: theme.textTheme.bodyMedium)), SizedBox(height: 54.v), _buildWalletEmpty(context), SizedBox(height: 15.v), _buildTabview(context), _buildTabBarView(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft(context);}), actions: [AppbarTrailingButton(margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 8.v), onTap: () {onTapSkip(context);})]); } 
/// Section Widget
Widget _buildWalletEmpty(BuildContext context) { return Align(alignment: Alignment.center, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.blueGray80001, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 180.v, width: 327.h, decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSubtractWhiteA700, height: 97.v, width: 130.h, alignment: Alignment.topRight), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Your name", style: CustomTextStyles.titleSmallWhiteA700), SizedBox(height: 41.v), Text("----   ----   ----   ----", style: CustomTextStyles.titleMediumWhiteA700_1), SizedBox(height: 22.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Balance", style: CustomTextStyles.labelSmallWhiteA700), SizedBox(height: 4.v), Text("  ------", style: CustomTextStyles.titleSmallWhiteA700_1)]), CustomImageView(imagePath: ImageConstant.imgThumbsUpWhiteA700, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 7.v, bottom: 3.v))])])))])))); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 50.v, width: 368.h, child: TabBar(controller: tabviewController, isScrollable: true, tabs: [Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionIndigo90020x20, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("Paypal"))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUser11x20, height: 11.v, width: 20.h, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("MasterCard"))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSettingsIndigo90001, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Text("Visa"))]))])); } 
/// Section Widget
Widget _buildTabBarView(BuildContext context) { return Expanded(child: SizedBox(height: 272.v, child: TabBarView(controller: tabviewController, children: [PaymentEmptyPage(), PaymentEmptyPage(), PaymentEmptyPage()]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapSkip(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeContainerScreen); } 
 }
