import 'controller/when_is_your_birthday_controller.dart';import 'package:flutter/material.dart';import 'package:table_calendar/table_calendar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_text_form_field.dart';class WhenIsYourBirthdayScreen extends GetWidget<WhenIsYourBirthdayController> {const WhenIsYourBirthdayScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [Text("msg_your_birthday_will".tr, style: CustomTextStyles.titleMediumMedium), Spacer(flex: 51), CustomTextFormField(controller: controller.dateController, hintText: "lbl_27_12_1995".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconlyCurvedCalendar, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 22.h, top: 19.v, bottom: 19.v)), SizedBox(height: 32.v), _buildCalendar(), Spacer(flex: 48), SizedBox(height: 24.v), _buildAutoLayoutHorizontal()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "msg_when_is_your_birthday".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildCalendar() { return Obx(() => SizedBox(height: 176.v, width: 348.h, child: TableCalendar(locale: 'en_US', firstDay: DateTime(DateTime.now().year - 5), lastDay: DateTime(DateTime.now().year + 5), calendarFormat: CalendarFormat.month, rangeSelectionMode: controller.rangeSelectionMode.value, startingDayOfWeek: StartingDayOfWeek.sunday, headerStyle: HeaderStyle(formatButtonVisible: false, titleCentered: true), calendarStyle: CalendarStyle(outsideDaysVisible: false, isTodayHighlighted: true), daysOfWeekStyle: DaysOfWeekStyle(), focusedDay: controller.focusedDay.value, rangeStartDay: controller.rangeStart, rangeEndDay: controller.rangeEnd, onDaySelected: (selectedDay, focusedDay) {if (!isSameDay(controller.selectedDay, selectedDay)) {controller.focusedDay.value = focusedDay; controller.selectedDay = selectedDay; controller.rangeSelectionMode.value = RangeSelectionMode.toggledOn;}}, onRangeSelected: (start, end, focusedDay) {controller.focusedDay.value = focusedDay; controller.rangeEnd = end; controller.rangeStart = start; controller.rangeSelectionMode.value = RangeSelectionMode.toggledOn;}, onPageChanged: (focusedDay) {controller.focusedDay.value = focusedDay;}))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_skip".tr, margin: EdgeInsets.only(right: 6.h), buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary, onPressed: () {onTapSkip();})), Expanded(child: CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 6.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16, onPressed: () {onTapContinue();}))]); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapSkip() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
/// Navigates to the fillYourProfileBlankFormScreen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.fillYourProfileBlankFormScreen, ); } 
 }
