import 'notifier/add_new_card_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/custom_elevated_button.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/custom_text_form_field.dart';class AddNewCardScreen extends ConsumerStatefulWidget {const AddNewCardScreen({Key? key}) : super(key: key);

@override AddNewCardScreenState createState() =>  AddNewCardScreenState();

 }
class AddNewCardScreenState extends ConsumerState<AddNewCardScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [_buildFrame(context), SizedBox(height: 24.v), Divider(), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_card_name".tr, style: CustomTextStyles.titleMedium_1)), SizedBox(height: 13.v), _buildName(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_card_number".tr, style: CustomTextStyles.titleMedium_1)), SizedBox(height: 13.v), _buildCardNumber(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_expiry_date2".tr, style: CustomTextStyles.titleMedium_1)), Padding(padding: EdgeInsets.only(left: 100.h, bottom: 2.v), child: Text("lbl_cvv".tr, style: CustomTextStyles.titleMedium_1))])), SizedBox(height: 11.v), _buildCvv1(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAdd(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_add_new_card".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconlyLightScan, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.all(30.h), decoration: AppDecoration.gradientRedToOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_mocard".tr, style: CustomTextStyles.titleMediumWhiteA70016), CustomImageView(imagePath: ImageConstant.imgSettingsWhiteA700, height: 18.v, width: 60.h)]), SizedBox(height: 35.v), Align(alignment: Alignment.centerLeft, child: Text("msg".tr, style: CustomTextStyles.displayMediumWhiteA700)), SizedBox(height: 28.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_card_holder_name".tr, style: CustomTextStyles.labelMediumWhiteA700), SizedBox(height: 5.v), Text("lbl2".tr, style: CustomTextStyles.titleSmallWhiteA700)]), Spacer(flex: 42), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_expiry_date".tr, style: CustomTextStyles.labelMediumWhiteA700), SizedBox(height: 4.v), Text("lbl3".tr, style: CustomTextStyles.titleSmallWhiteA700)]), Spacer(flex: 57), CustomImageView(imagePath: ImageConstant.imgGroup, height: 36.v, width: 58.h)])])); } 
/// Section Widget
Widget _buildName(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(addNewCardNotifier).nameController, hintText: "lbl_andrew_ainsley".tr);}); } 
/// Section Widget
Widget _buildCardNumber(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(addNewCardNotifier).cardNumberController, hintText: "msg_2672_4738_7837_7285".tr);}); } 
/// Section Widget
Widget _buildCvv(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(addNewCardNotifier).cvvController, hintText: "lbl_699".tr, textInputAction: TextInputAction.done);}))); } 
/// Section Widget
Widget _buildCvv1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: GestureDetector(onTap: () {onTapInputFields(context);}, child: Container(margin: EdgeInsets.only(right: 10.h), padding: EdgeInsets.symmetric(vertical: 18.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Text("lbl_10_07_2026".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgIconsPrimary, height: 20.adaptSize, width: 20.adaptSize)])))), _buildCvv(context)]); } 
/// Section Widget
Widget _buildAdd(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapAdd(context);}); } 

/// Displays a date picker dialog to update the selected date
///
/// This function returns a `Future` that completes with `void`.
Future<void> onTapInputFields(BuildContext context) async  { DateTime? dateTime  = await showDatePicker(context: context!,initialDate: ref.watch(addNewCardNotifier.notifier).selectedInputFieldsDate ?? DateTime.now() , firstDate: DateTime(1970) ,lastDate: DateTime(DateTime.now().year,DateTime.now().month,DateTime.now().day)); if (dateTime != null) {ref.watch(addNewCardNotifier.notifier).selectedInputFieldsDate = dateTime;} } 
/// Navigates to the selectPaymentMethodScreen when the action is triggered.
onTapAdd(BuildContext context) { NavigatorService.pushNamed(AppRoutes.selectPaymentMethodScreen, ); } 
 }
