import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';class EditProfileScreen extends StatelessWidget {const EditProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [SizedBox(height: 160.adaptSize, width: 160.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse160x160, height: 160.adaptSize, width: 160.adaptSize, radius: BorderRadius.circular(80.h), alignment: Alignment.center), CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(3.h), alignment: Alignment.bottomRight, child: CustomImageView(imagePath: ImageConstant.imgEdit))])), SizedBox(height: 24.v), Divider(), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Text("About You", style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgLockGray900, username: "Name", andrewAinsley: "Andrew Ainsley"), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgIconlyCurvedTick, username: "Username", andrewAinsley: "andrew_ainsley"), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgIconlyCurvedInfo, username: "Bio", andrewAinsley: "Designer & Vid..."), SizedBox(height: 24.v), Divider(), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Text("Social", style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgCategoriesFacebookGray900, username: "Facebook", andrewAinsley: "AndrewAinsley"), SizedBox(height: 24.v), _buildCategoriesTwitter(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Edit Profile", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgCategoriesInstagramGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Instagram", style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("@andrew_ains..", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))]); } 
/// Section Widget
Widget _buildCategoriesTwitter(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCategoriesTwitter, height: 28.adaptSize, width: 28.adaptSize, onTap: () {onTapImgCategoriesTwitter(context);}), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text("Twitter", style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("Andrew_Ainsl...", style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgGroupGray900, height: 11.v, width: 5.h, margin: EdgeInsets.only(left: 27.h, top: 8.v, bottom: 8.v))])); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String iconlyCurvedTick, required String username, required String andrewAinsley, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: iconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text(username, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text(andrewAinsley, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))]); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
/// Opens a URL in the device's default web browser.
///
/// The [context] parameter is the `BuildContext` of the widget that invoked the function.
///
/// Throws an exception if the URL could not be launched.
onTapImgCategoriesTwitter(BuildContext context) async  { var url = 'https://twitter.com/login/';if(!await launchUrlString(url)) {throw 'Could not launch https://twitter.com/login/';} } 
 }
