import '../hotel_details_screen/widgets/framenineteen_item_widget.dart';import '../hotel_details_screen/widgets/photos_item_widget.dart';import 'dart:async';import 'models/framenineteen_item_model.dart';import 'models/hotel_details_model.dart';import 'models/photos_item_model.dart';import 'package:flutter/material.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';import 'package:readmore/readmore.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:the_5_07_comfort___hotel_booking_app/core/app_export.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/custom_drop_down.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/custom_elevated_button.dart';import 'provider/hotel_details_provider.dart';class HotelDetailsScreen extends StatefulWidget {const HotelDetailsScreen({Key? key}) : super(key: key);

@override HotelDetailsScreenState createState() =>  HotelDetailsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => HotelDetailsProvider(), child: HotelDetailsScreen()); } 
 }

// ignore_for_file: must_be_immutable
class HotelDetailsScreenState extends State<HotelDetailsScreen> {Completer<GoogleMapController> googleMapController = Completer();

@override void initState() { super.initState();NavigatorService.pushNamed(AppRoutes.galleryScreen, );NavigatorService.pushNamed(AppRoutes.selectDateGuestScreen, ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 11.v), child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildEightySeven(context), SizedBox(height: 24.v), _buildHotelDetails(context), SizedBox(height: 35.v), _buildGalleryPhotos(context), SizedBox(height: 32.v), _buildDetails(context), SizedBox(height: 33.v), _buildDescription(context), SizedBox(height: 31.v), _buildFacilites(context), SizedBox(height: 31.v), _buildLocation(context), SizedBox(height: 32.v), _buildReview(context), SizedBox(height: 40.v), _buildPrice(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 39.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownWhiteA700, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowDown(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgBookmark, margin: EdgeInsets.only(left: 24.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsWhiteA700, margin: EdgeInsets.only(left: 20.h, right: 24.h))]); } 
/// Section Widget
Widget _buildEightySeven(BuildContext context) { return SizedBox(height: 206.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle6, height: 206.v, width: 428.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 164.h, vertical: 12.v), decoration: AppDecoration.gradient, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 176.v), SizedBox(height: 6.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 5, effect: ScrollingDotsEffect(spacing: 11, activeDotColor: theme.colorScheme.primary, dotColor: appTheme.gray700, dotHeight: 6.v, dotWidth: 6.h)))])))])); } 
/// Section Widget
Widget _buildHotelDetails(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_royale_president".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 15.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_france".tr, style: CustomTextStyles.bodyMediumGray50))])])); } 
/// Section Widget
Widget _buildGalleryPhotos(BuildContext context) { return Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_gallery_photos".tr, style: theme.textTheme.titleMedium), GestureDetector(onTap: () {onTapTxtSeeAll(context);}, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumPrimary)))])), SizedBox(height: 16.v), Align(alignment: Alignment.centerRight, child: SizedBox(height: 100.v, child: Consumer<HotelDetailsProvider>(builder: (context, provider, child) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: provider.hotelDetailsModelObj.photosItemList.length, itemBuilder: (context, index) {PhotosItemModel model = provider.hotelDetailsModelObj.photosItemList[index]; return PhotosItemWidget(model);});})))]); } 
/// Section Widget
Widget _buildDetails(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_details".tr, style: theme.textTheme.titleMedium), SizedBox(height: 18.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 28.h, right: 19.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgFramePrimary, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 7.v), Text("lbl_hotels".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 41), Column(children: [CustomImageView(imagePath: ImageConstant.imgFramePrimary32x32, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 7.v), Text("lbl_4_bedrooms".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 27), Column(children: [CustomImageView(imagePath: ImageConstant.imgFrame32x32, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 7.v), Text("lbl_2_bathrooms".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 31), Column(children: [CustomImageView(imagePath: ImageConstant.imgFrame1, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 8.v), Text("lbl_4000_sqft".tr, style: theme.textTheme.labelLarge)])])))])); } 
/// Section Widget
Widget _buildDescription(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_description".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), SizedBox(width: 379.h, child: ReadMoreText("msg_lorem_ipsum_dolor2".tr, trimLines: 5, colorClickableText: theme.colorScheme.primary, trimMode: TrimMode.Line, trimCollapsedText: "lbl_read_more".tr, moreStyle: CustomTextStyles.bodyMediumGray50.copyWith(height: 1.50), lessStyle: CustomTextStyles.bodyMediumGray50.copyWith(height: 1.50)))])); } 
/// Section Widget
Widget _buildFacilites(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_facilites".tr, style: theme.textTheme.titleMedium), SizedBox(height: 22.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h, right: 20.h), child: Row(children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 24.v, width: 26.h), SizedBox(height: 12.v), Text("lbl_swimming_pool".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 29), Padding(padding: EdgeInsets.only(top: 2.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSettingsPrimary, height: 18.v, width: 26.h), SizedBox(height: 13.v), Text("lbl_wifi".tr, style: theme.textTheme.labelLarge)])), Spacer(flex: 37), Column(children: [CustomImageView(imagePath: ImageConstant.imgCut, height: 23.v, width: 25.h), SizedBox(height: 11.v), Text("lbl_restaurant".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 33), Column(children: [CustomImageView(imagePath: ImageConstant.imgWarning, height: 24.v, width: 32.h), SizedBox(height: 12.v), Text("lbl_parking".tr, style: theme.textTheme.labelLarge)])])), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Row(children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgUserPrimary, height: 26.v, width: 21.h), SizedBox(height: 11.v), Text("lbl_meeting_room".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 48), Column(children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 11.v), Text("lbl_elevator".tr, style: theme.textTheme.labelLarge)]), Spacer(flex: 51), Column(children: [CustomImageView(imagePath: ImageConstant.imgSettingsPrimary26x26, height: 26.adaptSize, width: 26.adaptSize), SizedBox(height: 9.v), Text("lbl_fitness_center".tr, style: theme.textTheme.labelLarge)]), Padding(padding: EdgeInsets.only(left: 19.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSettings26x26, height: 26.adaptSize, width: 26.adaptSize), SizedBox(height: 11.v), Text("lbl_24_hours_open".tr, style: theme.textTheme.labelLarge)]))]))])])); } 
/// Section Widget
Widget _buildLocation(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_location".tr, style: theme.textTheme.titleMedium), SizedBox(height: 18.v), SizedBox(height: 180.v, width: 380.h, child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false))])); } 
/// Section Widget
Widget _buildReview(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_review".tr, style: theme.textTheme.titleMedium), Container(width: 42.h, margin: EdgeInsets.only(left: 21.h, bottom: 2.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSignalYellowA700, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_8".tr, style: CustomTextStyles.titleMediumPrimarySemiBold))])), Padding(padding: EdgeInsets.only(left: 8.h, top: 4.v, bottom: 3.v), child: Text("lbl_4_981_reviews".tr, style: theme.textTheme.bodySmall)), Spacer(), GestureDetector(onTap: () {onTapTxtSeeAll1(context);}, child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumPrimary))]), SizedBox(height: 19.v), Consumer<HotelDetailsProvider>(builder: (context, provider, child) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: provider.hotelDetailsModelObj.framenineteenItemList.length, itemBuilder: (context, index) {FramenineteenItemModel model = provider.hotelDetailsModelObj.framenineteenItemList[index]; return FramenineteenItemWidget(model);});}), SizedBox(height: 20.v), Selector<HotelDetailsProvider, HotelDetailsModel?>(selector: (context, provider) => provider.hotelDetailsModelObj, builder: (context, hotelDetailsModelObj, child) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(16.h, 17.v, 30.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownPrimary, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_more".tr, hintStyle: CustomTextStyles.titleMedium16, items: hotelDetailsModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), borderDecoration: DropDownStyleHelper.fillGray, fillColor: appTheme.gray700, onChanged: (value) {context.read<HotelDetailsProvider>().onSelected(value);});})])); } 
/// Section Widget
Widget _buildPrice(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: Text("lbl_29".tr, style: CustomTextStyles.headlineLargePrimary)), Padding(padding: EdgeInsets.only(left: 4.h, top: 20.v, bottom: 21.v), child: Text("lbl_night".tr, style: CustomTextStyles.bodyMediumGray40001)), CustomElevatedButton(height: 58.v, width: 263.h, text: "lbl_book_now".tr, margin: EdgeInsets.only(left: 17.h), buttonStyle: CustomButtonStyles.outlineGreenAF, onPressed: () {onTapBookNow(context);})])); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the galleryScreen when the action is triggered.
onTapTxtSeeAll(BuildContext context) { NavigatorService.pushNamed(AppRoutes.galleryScreen, ); } 
/// Navigates to the reviewTabContainerScreen when the action is triggered.
onTapTxtSeeAll1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.reviewTabContainerScreen, ); } 
/// Navigates to the selectDateGuestScreen when the action is triggered.
onTapBookNow(BuildContext context) { NavigatorService.pushNamed(AppRoutes.selectDateGuestScreen, ); } 
 }
