import 'controller/history_detail_controller.dart';import 'package:flutter/material.dart';import 'package:the_4_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_subtitle.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_icon_button.dart';class HistoryDetailScreen extends GetWidget<HistoryDetailController> {const HistoryDetailScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 17.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [_buildEstatesCardTransaction(), SizedBox(height: 32.v), _buildTransactionDetail(), SizedBox(height: 38.v), _buildPaymentDetail(), SizedBox(height: 36.v), _buildPaymentMethod()]))))])), bottomNavigationBar: _buildReview())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "msg_transaction_detail".tr)); } 
/// Section Widget
Widget _buildEstatesCardTransaction() { return Container(padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [SizedBox(height: 140.v, width: 168.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgShape20, height: 140.v, width: 168.h, radius: BorderRadius.circular(18.h), alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillWhiteATL121, child: CustomImageView(imagePath: ImageConstant.imgFavoriteRedA200)), SizedBox(height: 75.v), CustomElevatedButton(height: 24.v, width: 72.h, text: "lbl_apartment".tr, leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 13.v, width: 11.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAfTL8, buttonTextStyle: CustomTextStyles.labelSmallGray100)])))])), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 88.h, child: Text("msg_sky_dandelions_apartment".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50))), SizedBox(height: 6.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 12.adaptSize, width: 12.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_jakarta_indonesia".tr, style: theme.textTheme.labelSmall))]), SizedBox(height: 18.v), CustomElevatedButton(height: 50.v, width: 94.h, text: "lbl_rent".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.fillWhiteATL25, buttonTextStyle: theme.textTheme.labelMedium!, alignment: Alignment.centerRight)]))])); } 
/// Section Widget
Widget _buildTransactionDetail() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_transaction_detail".tr, style: theme.textTheme.titleMedium), SizedBox(height: 22.v), Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 21.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [_buildCheckOut(checkOut: "lbl_check_in2".tr, oneMillionTwoHundredEightyTwoT: "lbl_11_28_2021".tr), SizedBox(height: 14.v), _buildCheckOut(checkOut: "lbl_check_out2".tr, oneMillionTwoHundredEightyTwoT: "lbl_01_28_2022".tr), SizedBox(height: 14.v), _buildCheckOut(checkOut: "lbl_owner_name".tr, oneMillionTwoHundredEightyTwoT: "lbl_anderson".tr), SizedBox(height: 15.v), _buildCheckOut(checkOut: "msg_transaction_type".tr, oneMillionTwoHundredEightyTwoT: "lbl_rent".tr)]))]); } 
/// Section Widget
Widget _buildPaymentDetail() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_payment_detail".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 24.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.customBorderTL25), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildCheckOut(checkOut: "lbl_period_time".tr, oneMillionTwoHundredEightyTwoT: "lbl_2_month".tr), SizedBox(height: 15.v), _buildCheckOut(checkOut: "lbl_monthly_payment".tr, oneMillionTwoHundredEightyTwoT: "lbl_220".tr), SizedBox(height: 13.v), _buildCheckOut(checkOut: "lbl_discount".tr, oneMillionTwoHundredEightyTwoT: "lbl_88".tr)])), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 24.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderBL25), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_total".tr, style: theme.textTheme.titleMedium), Text("lbl_31_250".tr, style: theme.textTheme.titleMedium)]))])]); } 
/// Section Widget
Widget _buildPaymentMethod() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_payment_method".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), Container(padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineBluegray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgTelevisionIndigo900, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v), child: Text("msg_an_email_com2".tr, style: theme.textTheme.bodySmall))]))]); } 
/// Section Widget
Widget _buildReview() { return Container(margin: EdgeInsets.only(bottom: 23.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_love_the_estate".tr, style: theme.textTheme.titleMedium), CustomElevatedButton(text: "msg_click_here_to_add".tr, margin: EdgeInsets.only(top: 16.v), onPressed: () {onTapClickHereToAddReview();})])); } 
/// Common widget
Widget _buildCheckOut({required String checkOut, required String oneMillionTwoHundredEightyTwoT, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(checkOut, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray600)), Text(oneMillionTwoHundredEightyTwoT, style: CustomTextStyles.labelLargeBluegray600.copyWith(color: appTheme.blueGray600))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the addReviewEmptyScreen when the action is triggered.
onTapClickHereToAddReview() { Get.toNamed(AppRoutes.addReviewEmptyScreen, ); } 
 }
