import 'controller/forgot_password_methods_controller.dart';import 'package:flutter/material.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';class ForgotPasswordMethodsScreen extends GetWidget<ForgotPasswordMethodsController> {const ForgotPasswordMethodsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 89.v, right: 24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 368.h, margin: EdgeInsets.only(right: 11.h), child: Text("msg_select_which_contact".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMedium.copyWith(height: 1.40)))), SizedBox(height: 21.v), _buildAutoLayoutHorizontal(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(), SizedBox(height: 24.v), CustomElevatedButton(text: "lbl_continue".tr, buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16, onPressed: () {onTapContinue();}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_forgot_password".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return Container(decoration: AppDecoration.outline.copyWith(borderRadius: BorderRadiusStyle.roundedBorder22), child: OutlineGradientButton(padding: EdgeInsets.only(left: 3.h, top: 3.v, right: 3.h, bottom: 3.v), strokeWidth: 3.h, gradient: LinearGradient(begin: Alignment(1, 1), end: Alignment(0, 0), colors: [appTheme.deepOrangeA400, appTheme.orange600]), corners: Corners(topLeft: Radius.circular(20), topRight: Radius.circular(20), bottomLeft: Radius.circular(20), bottomRight: Radius.circular(20)), child: Padding(padding: EdgeInsets.all(21.h), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: CustomImageView(imagePath: ImageConstant.imgIconlyBoldChat, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_sms".tr, style: CustomTextStyles.titleSmallGray600_1), SizedBox(height: 10.v), Text("lbl_1_111_99".tr, style: CustomTextStyles.titleMediumBlack900)]))])))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1() { return Container(padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder22), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: CustomImageView(imagePath: ImageConstant.imgIconlyBoldMessage, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_email".tr, style: CustomTextStyles.titleSmallGray600_1), SizedBox(height: 12.v), Text("msg_abc_g_gmail_com".tr, style: CustomTextStyles.titleMediumBlack900)]))])); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the forgotPasswordTypeOtpScreen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.forgotPasswordTypeOtpScreen, ); } 
 }
