import '../messages_screen/widgets/autolayouthorizontal7_item_widget.dart';import '../messages_screen/widgets/theresavarnes_item_widget.dart';import 'bloc/messages_bloc.dart';import 'models/autolayouthorizontal7_item_model.dart';import 'models/messages_model.dart';import 'models/theresavarnes_item_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_search_view.dart';class MessagesScreen extends StatelessWidget {const MessagesScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MessagesBloc>(create: (context) => MessagesBloc(MessagesState(messagesModelObj: MessagesModel()))..add(MessagesInitialEvent()), child: MessagesScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: BlocSelector<MessagesBloc, MessagesState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search".tr, alignment: Alignment.center);}))), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_recently".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 22.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_messages".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 21.v), _buildTheresaVarnes(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_messages".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgIconlyCurvedPlusGray900, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 14.h)), AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray900, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 38.h))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 104.v, child: BlocSelector<MessagesBloc, MessagesState, MessagesModel?>(selector: (state) => state.messagesModelObj, builder: (context, messagesModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: messagesModelObj?.autolayouthorizontal7ItemList.length ?? 0, itemBuilder: (context, index) {Autolayouthorizontal7ItemModel model = messagesModelObj?.autolayouthorizontal7ItemList[index] ?? Autolayouthorizontal7ItemModel(); return Autolayouthorizontal7ItemWidget(model);});}))); } 
/// Section Widget
Widget _buildTheresaVarnes(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: BlocSelector<MessagesBloc, MessagesState, MessagesModel?>(selector: (state) => state.messagesModelObj, builder: (context, messagesModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: messagesModelObj?.theresavarnesItemList.length ?? 0, itemBuilder: (context, index) {TheresavarnesItemModel model = messagesModelObj?.theresavarnesItemList[index] ?? TheresavarnesItemModel(); return TheresavarnesItemWidget(model, onTapTypeMessengerList: () {onTapTypeMessengerList(context);});});}))); } 
/// Navigates to the messagesBoxScreen when the action is triggered.
onTapTypeMessengerList(BuildContext context) { NavigatorService.pushNamed(AppRoutes.messagesBoxScreen); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
