import '../filter_page/widgets/home_item_widget.dart';import '../filter_page/widgets/options2_item_widget.dart';import 'controller/filter_controller.dart';import 'models/filter_model.dart';import 'models/home_item_model.dart';import 'models/options2_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_21_vertex___real_estate_app/core/app_export.dart';import 'package:the_4_21_vertex___real_estate_app/widgets/custom_drop_down.dart';import 'package:the_4_21_vertex___real_estate_app/widgets/custom_elevated_button.dart';import 'package:the_4_21_vertex___real_estate_app/widgets/custom_icon_button.dart';import 'package:the_4_21_vertex___real_estate_app/widgets/custom_outlined_button.dart';
// ignore_for_file: must_be_immutable
class FilterPage extends StatelessWidget {FilterPage({Key? key}) : super(key: key);

FilterController controller = Get.put(FilterController(FilterModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 27.v), Column(children: [_buildPriceRange(), SizedBox(height: 26.v), _buildFeatures(), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_property_facts".tr, style: CustomTextStyles.titleMedium16))), SizedBox(height: 17.v), _buildSquareFeet1(), SizedBox(height: 17.v), _buildSquareFeet2(), SizedBox(height: 27.v), _buildPropertyType(), SizedBox(height: 26.v), _buildAmenities(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Row(children: [Text("lbl_see_more".tr, style: CustomTextStyles.titleSmallPrimaryBold), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h, bottom: 2.v))]))), SizedBox(height: 24.v), _buildBTN()])]))))); } 
/// Section Widget
Widget _buildPriceRange() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_price_range".tr, style: CustomTextStyles.titleMedium16), Text("lbl_200_15_000".tr, style: CustomTextStyles.titleSmallPrimary_2)]), SizedBox(height: 22.v), SizedBox(height: 24.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: SizedBox(width: 327.h, child: Divider(color: appTheme.gray300)))), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildButton(), Padding(padding: EdgeInsets.only(top: 14.v, bottom: 7.v), child: SizedBox(width: 103.h, child: Divider(color: theme.colorScheme.primary))), _buildButton()]))]))])); } 
/// Section Widget
Widget _buildFeatures() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_features".tr, style: CustomTextStyles.titleMedium16), SizedBox(height: 20.v), Column(children: [_buildBaths(baths: "lbl_beds".tr, two: "lbl_42".tr), SizedBox(height: 16.v), _buildBaths(baths: "lbl_baths".tr, two: "lbl_2".tr)])])); } 
/// Section Widget
Widget _buildSquareFeet() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_square_feet".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_min".tr, items: controller.filterModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildSquareFeet1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [_buildSquareFeet(), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 16.h, top: 41.v, bottom: 13.v)), Padding(padding: EdgeInsets.only(left: 17.h, top: 26.v), child: CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_max".tr, items: controller.filterModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);}))])); } 
/// Section Widget
Widget _buildSquareFeet2() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_lot_size".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_min".tr, items: controller.filterModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);}), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 15.v, bottom: 14.v)), CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_max".tr, items: controller.filterModelObj.value.dropdownItemList3!.value, onChanged: (value) {controller.onSelected3(value);})])])); } 
/// Section Widget
Widget _buildPropertyType() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_property_type".tr, style: CustomTextStyles.titleMedium16), SizedBox(height: 14.v), Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.filterModelObj.value.homeItemList.value.length, (index) {HomeItemModel model = controller.filterModelObj.value.homeItemList.value[index]; return HomeItemWidget(model);})))])); } 
/// Section Widget
Widget _buildAmenities() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_amenities".tr, style: CustomTextStyles.titleMedium16), CustomImageView(imagePath: ImageConstant.imgVideoCamera, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 26.h))]), SizedBox(height: 16.v), Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.filterModelObj.value.options2ItemList.value.length, (index) {Options2ItemModel model = controller.filterModelObj.value.options2ItemList.value[index]; return Options2ItemWidget(model);})))])); } 
/// Section Widget
Widget _buildBTN() { return Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), decoration: AppDecoration.outlineBlueGrayF, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_reset".tr, margin: EdgeInsets.only(right: 7.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL10, buttonTextStyle: CustomTextStyles.titleMediumPrimaryBold)), Expanded(child: CustomElevatedButton(text: "lbl_apply".tr, margin: EdgeInsets.only(left: 7.h)))])); } 
/// Common widget
Widget _buildButton() { return Container(width: 24.h, padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 7.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgChevronLeft, height: 10.adaptSize, width: 10.adaptSize), CustomImageView(imagePath: ImageConstant.imgChevronRight, height: 10.adaptSize, width: 10.adaptSize)])); } 
/// Common widget
Widget _buildBaths({required String baths, required String two, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text(baths, style: CustomTextStyles.titleMediumMedium.copyWith(color: theme.colorScheme.primaryContainer)), Spacer(), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray300)), Padding(padding: EdgeInsets.only(left: 15.h), child: Text(two, style: CustomTextStyles.titleMedium16.copyWith(color: theme.colorScheme.primaryContainer))), Padding(padding: EdgeInsets.only(left: 15.h), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgFloatingIcon)))]); } 
 }
