import 'bloc/manage_accounts_bloc.dart';import 'models/manage_accounts_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';class ManageAccountsScreen extends StatelessWidget {const ManageAccountsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ManageAccountsBloc>(create: (context) => ManageAccountsBloc(ManageAccountsState(manageAccountsModelObj: ManageAccountsModel()))..add(ManageAccountsInitialEvent()), child: ManageAccountsScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ManageAccountsBloc, ManageAccountsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_account_information".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedMessage: ImageConstant.imgIconlyCurvedCall, email: "lbl_phone_number".tr, andrewAins: "lbl_1_123_456_789".tr, arrowRight: ImageConstant.imgArrowRightGray900), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedMessage: ImageConstant.imgIconlyCurvedMessage, email: "lbl_email".tr, andrewAins: "lbl_andrew_ains2".tr, arrowRight: ImageConstant.imgArrowRightGray900), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedMessage: ImageConstant.imgIconlyCurvedCalendar, email: "lbl_date_of_birth".tr, andrewAins: "lbl_27_12_1995".tr, arrowRight: ImageConstant.imgCalendar), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_account_control".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedDelete, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 4.v), child: Text("lbl_delete_account".tr, style: CustomTextStyles.titleMediumRedA200))])), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_manage_accounts".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("msg_switch_to_business".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 91.h, top: 4.v, bottom: 4.v))]); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String iconlyCurvedMessage, required String email, required String andrewAins, required String arrowRight, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: iconlyCurvedMessage, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text(email, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text(andrewAins, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), CustomImageView(imagePath: arrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))]); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
