import 'notifier/edit_profile_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_6_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';import 'package:the_6_16_tikpik___short_video__social_networking/domain/facebookauth/facebook_auth_helper.dart';class EditProfileScreen extends ConsumerStatefulWidget {const EditProfileScreen({Key? key}) : super(key: key);

@override EditProfileScreenState createState() =>  EditProfileScreenState();

 }
class EditProfileScreenState extends ConsumerState<EditProfileScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [SizedBox(height: 160.adaptSize, width: 160.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse160x160, height: 160.adaptSize, width: 160.adaptSize, radius: BorderRadius.circular(80.h), alignment: Alignment.center), CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(3.h), alignment: Alignment.bottomRight, child: CustomImageView(imagePath: ImageConstant.imgEdit))])), SizedBox(height: 24.v), Divider(), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_about_you".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgLockGray900, username: "lbl_name".tr, andrewAinsley: "lbl_andrew_ainsley".tr), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgIconlyCurvedTick, username: "lbl_username".tr, andrewAinsley: "lbl_andrew_ainsley2".tr), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgIconlyCurvedInfo, username: "lbl_bio".tr, andrewAinsley: "msg_designer_vid".tr), SizedBox(height: 24.v), Divider(), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_social".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal(context, iconlyCurvedTick: ImageConstant.imgCategoriesFacebookGray900, username: "lbl_facebook".tr, andrewAinsley: "lbl_andrewainsley2".tr, onTapAutoLayoutHorizontal: () {onTapAutoLayoutHorizontal(context);}), SizedBox(height: 24.v), _buildCategoriesTwitter(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_edit_profile".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgCategoriesInstagramGray900, height: 28.adaptSize, width: 28.adaptSize, onTap: () {onTapImgCategoriesInstagram(context);}), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_instagram".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("lbl_andrew_ains".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))]); } 
/// Section Widget
Widget _buildCategoriesTwitter(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCategoriesTwitter, height: 28.adaptSize, width: 28.adaptSize, onTap: () {onTapImgCategoriesTwitter(context);}), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text("lbl_twitter".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("lbl_andrew_ainsl".tr, style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgGroupGray900, height: 11.v, width: 5.h, margin: EdgeInsets.only(left: 27.h, top: 8.v, bottom: 8.v))])); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String iconlyCurvedTick, required String username, required String andrewAinsley, Function? onTapAutoLayoutHorizontal, }) { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: iconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text(username, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text(andrewAinsley, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray900))), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))])); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
/// Requests permission to access the camera and storage, and displays a model
/// sheet for selecting images.
///
/// Throws an error if permission is denied or an error occurs while selecting images.
onTapImgCategoriesInstagram(BuildContext context) async  { await PermissionManager.askForPermission(Permission.camera);await PermissionManager.askForPermission(Permission.storage);List<String?>? imageList = [];await FileManager().showModelSheetForImage(getImages: (value) async {imageList = value;}); } 
onTapAutoLayoutHorizontal(BuildContext context) async  {             await FacebookAuthHelper().facebookSignInProcess().then((facebookUser) {
              //TODO Actions to be performed after signin
              }).catchError((onError) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(onError.toString())));
            });
             } 
/// Opens a URL in the device's default web browser.
///
/// The [context] parameter is the `BuildContext` of the widget that invoked the function.
///
/// Throws an exception if the URL could not be launched.
onTapImgCategoriesTwitter(BuildContext context) async  { var url = 'https://twitter.com/login/';if(!await launchUrlString(url)) {throw 'Could not launch https://twitter.com/login/';} } 
 }
