import '../notifications_screen/widgets/notifications_item_widget.dart';import 'models/notifications_item_model.dart';import 'models/notifications_model.dart';import 'package:flutter/material.dart';import 'package:the_5_07_comfort___hotel_booking_app/core/app_export.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/custom_app_bar.dart';import 'provider/notifications_provider.dart';class NotificationsScreen extends StatefulWidget {const NotificationsScreen({Key? key}) : super(key: key);

@override NotificationsScreenState createState() =>  NotificationsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => NotificationsProvider(), child: NotificationsScreen()); } 
 }
class NotificationsScreenState extends State<NotificationsScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_today".tr, style: CustomTextStyles.titleMediumSemiBold_1)), SizedBox(height: 18.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_yesterday".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 22.v), _buildNotifications(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_notifications".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsWhiteA700, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 13.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.outlineBlackC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgCheckmarkPrimary80x83, height: 80.v, width: 83.h), Padding(padding: EdgeInsets.only(top: 18.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_payment_successful".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), Text("msg_laluna_hotel_booking".tr, style: CustomTextStyles.titleSmallGray40001)]))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.outlineBlackC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgFloatingIconCyan500, height: 80.v, width: 83.h), Padding(padding: EdgeInsets.symmetric(vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_e_wallet_connected".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), Text("msg_e_wallet_has_been".tr, style: CustomTextStyles.titleSmallGray40001)]))])); } 
/// Section Widget
Widget _buildNotifications(BuildContext context) { return Consumer<NotificationsProvider>(builder: (context, provider, child) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: provider.notificationsModelObj.notificationsItemList.length, itemBuilder: (context, index) {NotificationsItemModel model = provider.notificationsModelObj.notificationsItemList[index]; return NotificationsItemWidget(model);});}); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
