import '../add_new_property_reason_selling_home_screen/widgets/addnewpropertyreasonsellinghom_item_widget.dart';import 'bloc/add_new_property_reason_selling_home_bloc.dart';import 'models/add_new_property_reason_selling_home_model.dart';import 'models/addnewpropertyreasonsellinghom_item_model.dart';import 'package:flutter/material.dart';import 'package:the_3_21_vertex___real_estate_app/core/app_export.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/custom_checkbox_button.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/custom_elevated_button.dart';class AddNewPropertyReasonSellingHomeScreen extends StatelessWidget {const AddNewPropertyReasonSellingHomeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AddNewPropertyReasonSellingHomeBloc>(create: (context) => AddNewPropertyReasonSellingHomeBloc(AddNewPropertyReasonSellingHomeState(addNewPropertyReasonSellingHomeModelObj: AddNewPropertyReasonSellingHomeModel()))..add(AddNewPropertyReasonSellingHomeInitialEvent()), child: AddNewPropertyReasonSellingHomeScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [_buildAddressAndProgress(context), SizedBox(height: 16.v), Container(height: 6.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray300, borderRadius: BorderRadius.circular(3.h)), child: ClipRRect(borderRadius: BorderRadius.circular(3.h), child: LinearProgressIndicator(value: 0.5, backgroundColor: appTheme.gray300, valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Text("msg_why_are_you_selling".tr, style: CustomTextStyles.titleMediumBold_1)), SizedBox(height: 13.v), _buildAddNewPropertyReasonsellinghom(context), SizedBox(height: 8.v), _buildStreetAddress(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBTN(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_add_new_property".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildAddressAndProgress(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 8.v, bottom: 4.v), child: Text("msg_reason_selling_home".tr, style: theme.textTheme.titleSmall)), CustomElevatedButton(height: 33.v, width: 79.h, text: "lbl_04_08".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700)]); } 
/// Section Widget
Widget _buildAddNewPropertyReasonsellinghom(BuildContext context) { return BlocSelector<AddNewPropertyReasonSellingHomeBloc, AddNewPropertyReasonSellingHomeState, AddNewPropertyReasonSellingHomeModel?>(selector: (state) => state.addNewPropertyReasonSellingHomeModelObj, builder: (context, addNewPropertyReasonSellingHomeModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 8.v);}, itemCount: addNewPropertyReasonSellingHomeModelObj?.addnewpropertyreasonsellinghomItemList.length ?? 0, itemBuilder: (context, index) {AddnewpropertyreasonsellinghomItemModel model = addNewPropertyReasonSellingHomeModelObj?.addnewpropertyreasonsellinghomItemList[index] ?? AddnewpropertyreasonsellinghomItemModel(); return AddnewpropertyreasonsellinghomItemWidget(model);});}); } 
/// Section Widget
Widget _buildStreetAddress(BuildContext context) { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineGray300.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [BlocSelector<AddNewPropertyReasonSellingHomeBloc, AddNewPropertyReasonSellingHomeState, bool?>(selector: (state) => state.other, builder: (context, other) {return CustomCheckboxButton(text: "lbl_other".tr, value: other, onChange: (value) {context.read<AddNewPropertyReasonSellingHomeBloc>().add(ChangeCheckBoxEvent(value: value));});}), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 28.h), child: Text("msg_please_enter_your".tr, style: CustomTextStyles.bodySmallPrimaryContainer_1)), SizedBox(height: 10.v), Align(alignment: Alignment.centerRight, child: Container(width: 263.h, margin: EdgeInsets.only(left: 28.h, right: 4.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillGray300.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Container(width: 210.h, margin: EdgeInsets.only(right: 28.h), child: Text("msg_e_g_i_m_helping".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.50)))])))])); } 
/// Section Widget
Widget _buildBTN(BuildContext context) { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), decoration: AppDecoration.outlineBlueGrayF, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNext(context);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the addNewPropertyDecsriptionScreen when the action is triggered.
onTapNext(BuildContext context) { NavigatorService.pushNamed(AppRoutes.addNewPropertyDecsriptionScreen, ); } 
 }
