import '../profile_two_page/widgets/autolayoutvertical6_item_widget.dart';import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_outlined_button.dart';class ProfileTwoPage extends StatelessWidget {const ProfileTwoPage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 28.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [SizedBox(height: 120.adaptSize, width: 120.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse29, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center), CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(2.h), alignment: Alignment.bottomRight, onTap: () {onTapBtnEdit(context);}, child: CustomImageView(imagePath: ImageConstant.imgEdit))])), SizedBox(height: 14.v), Text("@andrew_aisnley", style: theme.textTheme.titleLarge), SizedBox(height: 9.v), Text("Designer & Videographer", style: CustomTextStyles.titleSmallGray900), SizedBox(height: 19.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 24.v), CustomOutlinedButton(height: 45.v, text: "Edit Profile", leftIcon: Container(margin: EdgeInsets.only(right: 9.h), child: CustomImageView(imagePath: ImageConstant.imgUserPrimary, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimaryTL16, buttonTextStyle: CustomTextStyles.titleMediumPrimary_1), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 23.v), _buildAutoLayoutVertical3(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 44.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgUserGray900, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v)), centerTitle: true, title: AppbarTitle(text: "Profile"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconlyCurvedSettingGray900, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), onTap: () {onTapIconlyCurvedSetting(context);})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 20.h, right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(children: [Text("247", style: theme.textTheme.headlineSmall), SizedBox(height: 5.v), Text("Posts", style: CustomTextStyles.titleSmallErrorContainer)]), Spacer(flex: 37), _buildAutoLayoutVertical(context, threeHundredSeventyFour: "368K", following: "Followers"), Spacer(flex: 30), _buildAutoLayoutVertical(context, threeHundredSeventyFour: "374", following: "Following"), Spacer(flex: 32), Column(children: [Text("3.7M", style: theme.textTheme.headlineSmall), SizedBox(height: 5.v), Text("Likes", style: CustomTextStyles.titleSmallErrorContainer)])])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 35.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgGrid, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 12.v), SizedBox(width: 95.h, child: Divider(color: theme.colorScheme.primary))]), Spacer(flex: 20), CustomImageView(imagePath: ImageConstant.imgLocation, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 16.v)), Spacer(flex: 39), CustomImageView(imagePath: ImageConstant.imgBookmarkGray500, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 16.v)), Spacer(flex: 39), CustomImageView(imagePath: ImageConstant.imgFavoriteGray500, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 16.v))]))); } 
/// Section Widget
Widget _buildAutoLayoutVertical3(BuildContext context) { return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 201.v, crossAxisCount: 2, mainAxisSpacing: 8.h, crossAxisSpacing: 8.h), physics: NeverScrollableScrollPhysics(), itemCount: 5, itemBuilder: (context, index) {return Autolayoutvertical6ItemWidget();}); } 
/// Common widget
Widget _buildAutoLayoutVertical(BuildContext context, {required String threeHundredSeventyFour, required String following, }) { return Column(children: [Text(threeHundredSeventyFour, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray900)), SizedBox(height: 6.v), Text(following, style: CustomTextStyles.titleSmallErrorContainer.copyWith(color: theme.colorScheme.errorContainer))]); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapIconlyCurvedSetting(BuildContext context) { Navigator.pushNamed(context, AppRoutes.settingsScreen); } 
/// Navigates to the editProfileScreen when the action is triggered.
onTapBtnEdit(BuildContext context) { Navigator.pushNamed(context, AppRoutes.editProfileScreen); } 
 }
