import '../real_estates_list_by_category_screen/widgets/datalist_item_widget.dart';import '../real_estates_list_by_category_screen/widgets/realestateslistbycategory_item_widget.dart';import 'models/datalist_item_model.dart';import 'models/real_estates_list_by_category_model.dart';import 'models/realestateslistbycategory_item_model.dart';import 'package:flutter/material.dart';import 'package:the_5_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_5_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_5_17_housit___buyrentsell_property/widgets/custom_icon_button.dart';import 'package:the_5_17_housit___buyrentsell_property/widgets/custom_search_view.dart';import 'provider/real_estates_list_by_category_provider.dart';class RealEstatesListByCategoryScreen extends StatefulWidget {const RealEstatesListByCategoryScreen({Key? key}) : super(key: key);

@override RealEstatesListByCategoryScreenState createState() =>  RealEstatesListByCategoryScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => RealEstatesListByCategoryProvider(), child: RealEstatesListByCategoryScreen()); } 
 }
class RealEstatesListByCategoryScreenState extends State<RealEstatesListByCategoryScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildHeader(context), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_top_villa".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 14.v), _buildDataList(context), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 18.h, right: 30.h), child: Selector<RealEstatesListByCategoryProvider, TextEditingController?>(selector: (context, provider) => provider.searchController, builder: (context, searchController, child) {return CustomSearchView(controller: searchController, hintText: "msg_search_in_villa_s".tr, contentPadding: EdgeInsets.symmetric(vertical: 26.v));})), SizedBox(height: 33.v), _buildItemHeader(context), SizedBox(height: 20.v), _buildRealEstatesListbyCategory(context), SizedBox(height: 20.v)]))))); } 
/// Section Widget
Widget _buildHeader(BuildContext context) { return SizedBox(height: 330.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBackground, height: 330.v, width: 375.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillWhiteA, onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft)), CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(15.h), decoration: IconButtonStyleHelper.fillWhiteA, child: CustomImageView(imagePath: ImageConstant.imgIconSetting))]), SizedBox(height: 179.v), CustomElevatedButton(height: 53.v, width: 89.h, text: "lbl_villa".tr, leftIcon: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 23.v, width: 19.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAf, buttonTextStyle: CustomTextStyles.labelLargeGray100Medium)])))])); } 
/// Section Widget
Widget _buildDataList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 156.v, child: Consumer<RealEstatesListByCategoryProvider>(builder: (context, provider, child) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: provider.realEstatesListByCategoryModelObj.datalistItemList.length, itemBuilder: (context, index) {DatalistItemModel model = provider.realEstatesListByCategoryModelObj.datalistItemList[index]; return DatalistItemWidget(model);});}))); } 
/// Section Widget
Widget _buildItemHeader(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 7.v), child: Text("lbl_120".tr, style: CustomTextStyles.titleMediumRedA200)), Padding(padding: EdgeInsets.only(left: 5.h, top: 9.v, bottom: 8.v), child: Text("lbl_villa".tr, style: CustomTextStyles.titleMediumMedium)), Spacer(), Container(width: 93.h, padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Container(height: 24.v, width: 36.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomImageView(imagePath: ImageConstant.imgGrid, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center)), Container(height: 24.v, width: 36.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomImageView(imagePath: ImageConstant.imgIconHorizontalOnprimarycontainer, height: 12.adaptSize, width: 12.adaptSize, alignment: Alignment.center))]))]))); } 
/// Section Widget
Widget _buildRealEstatesListbyCategory(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Consumer<RealEstatesListByCategoryProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 232.v, crossAxisCount: 2, mainAxisSpacing: 7.h, crossAxisSpacing: 7.h), physics: NeverScrollableScrollPhysics(), itemCount: provider.realEstatesListByCategoryModelObj.realestateslistbycategoryItemList.length, itemBuilder: (context, index) {RealestateslistbycategoryItemModel model = provider.realEstatesListByCategoryModelObj.realestateslistbycategoryItemList[index]; return RealestateslistbycategoryItemWidget(model);});}))); } 

/// Navigates to the previous screen.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
