import 'controller/posts_edit_page_controller.dart';import 'package:flutter/material.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title_button.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';class PostsEditPageScreen extends GetWidget<PostsEditPageController> {const PostsEditPageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer, image: DecorationImage(image: AssetImage(ImageConstant.imgPostsQuickPhoto), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 32.v), SizedBox(height: 850.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 200.v, width: double.maxFinite, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [theme.colorScheme.primaryContainer, theme.colorScheme.primaryContainer.withOpacity(0.6)])))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [_buildAppBar(), SizedBox(height: 20.v), CustomImageView(imagePath: ImageConstant.imgCategoriesFont, height: 36.adaptSize, width: 36.adaptSize, margin: EdgeInsets.only(right: 2.h)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 10.h), child: Text("lbl_flip".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 18.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgCategoriesSticker, flip: "lbl_flip".tr), SizedBox(height: 18.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgCategoriesFilterOnerrorcontainer, flip: "lbl_flip".tr), SizedBox(height: 18.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgCategoriesSubtitle, flip: "lbl_speed".tr), SizedBox(height: 18.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgLocationOnerrorcontainer, flip: "lbl_filters".tr), SizedBox(height: 19.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgUser, flip: "lbl_beauty".tr), SizedBox(height: 18.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgMenu, flip: "lbl_timer".tr), SizedBox(height: 19.v), _buildAutoLayoutVertical(categoriesFilter: ImageConstant.imgCategoriesEnhance, flip: "lbl_reply".tr), SizedBox(height: 18.v), CustomImageView(imagePath: ImageConstant.imgCategoriesFlash, height: 36.adaptSize, width: 36.adaptSize, margin: EdgeInsets.only(right: 2.h)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 5.h), child: Text("lbl_flash".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 39.v), _buildAutoLayoutHorizontal()])))]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 32.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownOnerrorcontainer, margin: EdgeInsets.only(left: 24.h, top: 2.v, bottom: 2.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitleButton()); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_post_to_story".tr, margin: EdgeInsets.only(right: 6.h), buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary)), Expanded(child: CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 6.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16))]); } 
/// Common widget
Widget _buildAutoLayoutVertical({required String categoriesFilter, required String flip, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 26.h), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: categoriesFilter, height: 36.adaptSize, width: 36.adaptSize), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 8.h), child: Text(flip, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.onErrorContainer)))])); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
