import 'models/forgot_password_type_otp_model.dart';import 'package:flutter/material.dart';import 'package:the_5_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/custom_pin_code_text_field.dart';import 'provider/forgot_password_type_otp_provider.dart';class ForgotPasswordTypeOtpScreen extends StatefulWidget {const ForgotPasswordTypeOtpScreen({Key? key}) : super(key: key);

@override ForgotPasswordTypeOtpScreenState createState() =>  ForgotPasswordTypeOtpScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ForgotPasswordTypeOtpProvider(), child: ForgotPasswordTypeOtpScreen()); } 
 }
class ForgotPasswordTypeOtpScreenState extends State<ForgotPasswordTypeOtpScreen> {@override void initState() { super.initState();NavigatorService.pushNamed(AppRoutes.forgotPasswordFilledOtpScreen, ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 118.v, right: 24.h), child: Column(children: [Text("msg_code_has_been_send".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 61.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Selector<ForgotPasswordTypeOtpProvider, TextEditingController?>(selector: (context, provider) => provider.otpController, builder: (context, otpController, child) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), SizedBox(height: 60.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_resend_code_in".tr, style: CustomTextStyles.titleMediumMedium_1), TextSpan(text: "lbl_55".tr, style: CustomTextStyles.titleMediumPrimaryMedium), TextSpan(text: "lbl_s".tr, style: CustomTextStyles.titleMediumMedium_1)]), textAlign: TextAlign.left), SizedBox(height: 98.v), CustomElevatedButton(text: "lbl_verify".tr, buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_forgot_password".tr, margin: EdgeInsets.only(left: 16.h))); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
