import '../charts_screen/widgets/topalbumsglobal1_item_widget.dart';import '../charts_screen/widgets/topalbumsglobal_item_widget.dart';import 'package:flutter/material.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_7_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';class ChartsScreen extends StatelessWidget {const ChartsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 907.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topLeft, child: Text("Weekly Album Charts", style: theme.textTheme.headlineSmall)), SizedBox(width: double.maxFinite, child: Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Weekly Album Charts", style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildTOPALBUMSGLOBAL(context), SizedBox(height: 30.v), Text("Weekly Song Charts", style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildTOPALBUMSGLOBAL1(context)])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Charts", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildTOPALBUMSGLOBAL(BuildContext context) { return Expanded(child: SizedBox(height: 222.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 2, itemBuilder: (context, index) {return TopalbumsglobalItemWidget(onTapCard: () {onTapCard(context);});}))); } 
/// Section Widget
Widget _buildTOPALBUMSGLOBAL1(BuildContext context) { return SizedBox(height: 222.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 2, itemBuilder: (context, index) {return Topalbumsglobal1ItemWidget();})); } 
/// Navigates to the topAlbumsGlobalScreen when the action is triggered.
onTapCard(BuildContext context) { Navigator.pushNamed(context, AppRoutes.topAlbumsGlobalScreen); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
 }
