import '../charts_screen/widgets/topalbumsglobal1_item_widget.dart';import '../charts_screen/widgets/topalbumsglobal_item_widget.dart';import 'controller/charts_controller.dart';import 'models/topalbumsglobal1_item_model.dart';import 'models/topalbumsglobal_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_4_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';class ChartsScreen extends GetWidget<ChartsController> {const ChartsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(height: 907.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topLeft, child: Text("msg_weekly_album_charts".tr, style: theme.textTheme.headlineSmall)), SizedBox(width: double.maxFinite, child: Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_weekly_album_charts".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildTOPALBUMSGLOBAL(), SizedBox(height: 30.v), Text("msg_weekly_song_charts".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildTOPALBUMSGLOBAL1()])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_charts".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildTOPALBUMSGLOBAL() { return Expanded(child: SizedBox(height: 222.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.chartsModelObj.value.topalbumsglobalItemList.value.length, itemBuilder: (context, index) {TopalbumsglobalItemModel model = controller.chartsModelObj.value.topalbumsglobalItemList.value[index]; return TopalbumsglobalItemWidget(model, onTapCard: () {onTapCard();});})))); } 
/// Section Widget
Widget _buildTOPALBUMSGLOBAL1() { return SizedBox(height: 222.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.chartsModelObj.value.topalbumsglobal1ItemList.value.length, itemBuilder: (context, index) {Topalbumsglobal1ItemModel model = controller.chartsModelObj.value.topalbumsglobal1ItemList.value[index]; return Topalbumsglobal1ItemWidget(model);}))); } 
/// Navigates to the topAlbumsGlobalScreen when the action is triggered.
onTapCard() { Get.toNamed(AppRoutes.topAlbumsGlobalScreen); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
