import '../choose_your_interest_screen/widgets/sizelargetypeborder_item_widget.dart';import 'controller/choose_your_interest_controller.dart';import 'models/sizelargetypeborder_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';class ChooseYourInterestScreen extends GetWidget<ChooseYourInterestController> {const ChooseYourInterestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 367.h, margin: EdgeInsets.only(right: 12.h), child: Text("msg_choose_your_interests".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMedium.copyWith(height: 1.40))), SizedBox(height: 46.v), _buildSizeLargeTypeBorder(), SizedBox(height: 14.v), _buildSizeLargeTypeFilled(), Spacer(), SizedBox(height: 23.v), _buildAutoLayoutHorizontal()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "msg_choose_your_interest".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSizeLargeTypeBorder() { return Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.chooseYourInterestModelObj.value.sizelargetypeborderItemList.value.length, (index) {SizelargetypeborderItemModel model = controller.chooseYourInterestModelObj.value.sizelargetypeborderItemList.value[index]; return SizelargetypeborderItemWidget(model);}))); } 
/// Section Widget
Widget _buildSizeLargeTypeFilled() { return Padding(padding: EdgeInsets.only(right: 33.h), child: Row(children: [Container(width: 109.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder22), child: Text("lbl_culture".tr, style: CustomTextStyles.titleMediumOnErrorContainer_1)), Container(width: 103.h, margin: EdgeInsets.only(left: 13.h), padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v), decoration: AppDecoration.outlineGray600.copyWith(borderRadius: BorderRadiusStyle.roundedBorder22), child: Text("lbl_health".tr, style: CustomTextStyles.titleMediumGray600)), Container(width: 109.h, margin: EdgeInsets.only(left: 13.h), padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v), decoration: AppDecoration.outlineGray600.copyWith(borderRadius: BorderRadiusStyle.roundedBorder22), child: Text("lbl_comics".tr, style: CustomTextStyles.titleMediumGray600))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_skip".tr, margin: EdgeInsets.only(right: 6.h), buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary, onPressed: () {onTapSkip();})), Expanded(child: CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 6.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16, onPressed: () {onTapContinue();}))]); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapSkip() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
/// Navigates to the tellUsAboutYourselfScreen when the action is triggered.
onTapContinue() { Get.toNamed(AppRoutes.tellUsAboutYourselfScreen, ); } 
 }
