import '../find_friends_screen/widgets/findfriends_item_widget.dart';import 'bloc/find_friends_bloc.dart';import 'models/find_friends_model.dart';import 'models/findfriends_item_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_search_view.dart';class FindFriendsScreen extends StatelessWidget {const FindFriendsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<FindFriendsBloc>(create: (context) => FindFriendsBloc(FindFriendsState(findFriendsModelObj: FindFriendsModel()))..add(FindFriendsInitialEvent()), child: FindFriendsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 23.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [BlocSelector<FindFriendsBloc, FindFriendsState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search".tr);}), SizedBox(height: 24.v), _buildFindFriends(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_find_friends".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconlyCurvedScan, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v))]); } 
/// Section Widget
Widget _buildFindFriends(BuildContext context) { return BlocSelector<FindFriendsBloc, FindFriendsState, FindFriendsModel?>(selector: (state) => state.findFriendsModelObj, builder: (context, findFriendsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: findFriendsModelObj?.findfriendsItemList.length ?? 0, itemBuilder: (context, index) {FindfriendsItemModel model = findFriendsModelObj?.findfriendsItemList[index] ?? FindfriendsItemModel(); return FindfriendsItemWidget(model);});}); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
