import '../extra_information_screen/widgets/layout11_item_widget.dart';import '../extra_information_screen/widgets/layout6_item_widget.dart';import '../extra_information_screen/widgets/layout8_item_widget.dart';import '../extra_information_screen/widgets/layout9_item_widget.dart';import 'controller/extra_information_controller.dart';import 'models/layout11_item_model.dart';import 'models/layout6_item_model.dart';import 'models/layout8_item_model.dart';import 'models/layout9_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/appbar_subtitle.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_4_17_housit___buyrentsell_property/widgets/custom_text_form_field.dart';import 'package:the_4_17_housit___buyrentsell_property/presentation/extra_information_success_bottomsheet/extra_information_success_bottomsheet.dart';import 'package:the_4_17_housit___buyrentsell_property/presentation/extra_information_success_bottomsheet/controller/extra_information_success_controller.dart';class ExtraInformationScreen extends GetWidget<ExtraInformationController> {const ExtraInformationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 49.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 3.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 267.h, margin: EdgeInsets.only(right: 81.h), child: Text("msg_almost_finish_complete_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.50)))), SizedBox(height: 43.v), _buildSellPrice(), SizedBox(height: 37.v), _buildRentPrice(), SizedBox(height: 38.v), _buildPropertyFeatures(), SizedBox(height: 37.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_total_rooms".tr, style: CustomTextStyles.titleMediumBold)), SizedBox(height: 16.v), _buildLayout(), SizedBox(height: 36.v), _buildEnvironment(), SizedBox(height: 46.v), CustomImageView(imagePath: ImageConstant.imgProgressBarGradient, height: 1.v, width: 100.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 114.h))]))))])), bottomNavigationBar: _buildFinish())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 74.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 3.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_listing".tr)); } 
/// Section Widget
Widget _buildSellPrice() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sell_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 27.h), child: CustomTextFormField(controller: controller.priceController, hintText: "lbl_180_000".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v)))]); } 
/// Section Widget
Widget _buildRentPrice() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_rent_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(right: 24.h), child: CustomTextFormField(controller: controller.priceController1, hintText: "lbl_315".tr, hintStyle: CustomTextStyles.labelLargeSemiBold, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 25.v, 16.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgIconoirmail, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v))), SizedBox(height: 15.v), Obx(() => Wrap(runSpacing: 3.v, spacing: 3.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.layout6ItemList.value.length, (index) {Layout6ItemModel model = controller.extraInformationModelObj.value.layout6ItemList.value[index]; return Layout6ItemWidget(model);})))]); } 
/// Section Widget
Widget _buildPropertyFeatures() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_property_features".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(right: 21.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: controller.extraInformationModelObj.value.layout8ItemList.value.length, itemBuilder: (context, index) {Layout8ItemModel model = controller.extraInformationModelObj.value.layout8ItemList.value[index]; return Layout8ItemWidget(model);})))]); } 
/// Section Widget
Widget _buildLayout() { return Obx(() => Wrap(runSpacing: 10.v, spacing: 10.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.layout9ItemList.value.length, (index) {Layout9ItemModel model = controller.extraInformationModelObj.value.layout9ItemList.value[index]; return Layout9ItemWidget(model);}))); } 
/// Section Widget
Widget _buildEnvironment() { return Container(padding: EdgeInsets.symmetric(horizontal: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_environment_facilities".tr, style: CustomTextStyles.titleMediumBold), SizedBox(height: 16.v), Obx(() => Wrap(runSpacing: 4.v, spacing: 4.h, children: List<Widget>.generate(controller.extraInformationModelObj.value.layout11ItemList.value.length, (index) {Layout11ItemModel model = controller.extraInformationModelObj.value.layout11ItemList.value[index]; return Layout11ItemWidget(model);})))])); } 
/// Section Widget
Widget _buildFinish() { return CustomElevatedButton(text: "lbl_finish".tr, margin: EdgeInsets.only(left: 25.h, right: 23.h, bottom: 24.v), onPressed: () {onTapFinish();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [ExtraInformationSuccessBottomsheet] widget.
///
/// The bottom sheet is controlled by the [ExtraInformationSuccessController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapFinish() { Get.bottomSheet(ExtraInformationSuccessBottomsheet(Get.put(ExtraInformationSuccessController(),),),isScrollControlled: true,); } 
 }
