import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class TypeMessageScreen extends StatelessWidget {TypeMessageScreen({Key? key}) : super(key: key);

TextEditingController userController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 47.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 24.v, width: 75.h, text: "Today", buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumGray600, alignment: Alignment.center), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(right: 80.h), child: _buildAutoLayoutHorizontal(context, loremIpsumDolor: "Hi, morning too Andrew!", time: "10:00")), SizedBox(height: 10.v), Container(margin: EdgeInsets.only(right: 80.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 9.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderBL16), child: Row(crossAxisAlignment: CrossAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Container(width: 202.h, margin: EdgeInsets.only(top: 5.v), child: RichText(text: TextSpan(children: [TextSpan(text: "Yes you're right.\nI think we haven't talked in a long time ", style: theme.textTheme.bodyLarge!.copyWith(height: 1.40)), TextSpan(text: "😂😂", style: theme.textTheme.bodyLarge)]), textAlign: TextAlign.left))), Padding(padding: EdgeInsets.only(left: 29.h, top: 55.v, bottom: 2.v), child: Text("10:00", style: CustomTextStyles.bodySmallGray600))])), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 80.h), child: _buildAutoLayoutHorizontal(context, loremIpsumDolor: "Hi Theresa, good morning 😄", time: "10:00")), Spacer(flex: 28), _buildAutoLayoutHorizontal3(context), Spacer(flex: 71)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Theresa Varnes", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCall, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 10.h), onTap: () {onTapCall(context);}), AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray900, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 34.h))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3(BuildContext context) { return Row(children: [Expanded(child: CustomTextFormField(controller: userController, hintText: "Would you like to join us|", textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(22.h, 20.v, 13.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgUserPrimary16x16, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 21.v, 19.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgUserPrimary14x15, height: 14.v, width: 15.h)), suffixConstraints: BoxConstraints(maxHeight: 56.v))), Padding(padding: EdgeInsets.only(left: 12.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.gradientDeepOrangeAToOrange, child: CustomImageView(imagePath: ImageConstant.imgAutoLayoutHorizontalOnerrorcontainer56x56)))]); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String loremIpsumDolor, required String time, }) { return Container(width: 300.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 11.v), decoration: AppDecoration.gradientDeepOrangeAToOrange.copyWith(borderRadius: BorderRadiusStyle.customBorderTL16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text(loremIpsumDolor, style: CustomTextStyles.bodyLargeOnErrorContainer_1.copyWith(color: theme.colorScheme.onErrorContainer)), SizedBox(height: 7.v), Align(alignment: Alignment.centerRight, child: Text(time, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onErrorContainer)))])); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the callScreen when the action is triggered.
onTapCall(BuildContext context) { Navigator.pushNamed(context, AppRoutes.callScreen); } 
 }
