import '../../../core/app_export.dart';import 'promotionbanner_item_model.dart';import 'layout27_item_model.dart';import 'layout28_item_model.dart';import 'layout29_item_model.dart';import 'home_item_model.dart';class HomeModel {List<PromotionbannerItemModel> promotionbannerItemList = [PromotionbannerItemModel(halloweenSale: "Halloween \nSale!",offer: "All discount up to 60%"),PromotionbannerItemModel(halloweenSale: "Summer\nVacation",offer: "All discount up to 60%")];

List<Layout27ItemModel> layout27ItemList = [Layout27ItemModel(image:ImageConstant.imgShape61,favorite:ImageConstant.imgFavoriteRedA200,skyDandelionsApartment: "Sky Dandelions\nApartment",text: "4.9",jakartaIndonesia: "Jakarta, Indonesia",price: " 290",month: "/month"),Layout27ItemModel(image:ImageConstant.imgShape140x126,favorite:ImageConstant.imgFavorite,skyDandelionsApartment: "Sky Dandelions\nApartment",text: "4.2 ",jakartaIndonesia: "Jakarta, Indonesia",price: " 220",month: "/month")];

List<Layout28ItemModel> layout28ItemList = [Layout28ItemModel(bali:ImageConstant.imgShape40x40,bali1: "Bali"),Layout28ItemModel(bali:ImageConstant.imgShape62,bali1: "Jakarta"),Layout28ItemModel(bali:ImageConstant.imgShape63,bali1: "Yogyakarta"),Layout28ItemModel(bali:ImageConstant.imgShape64,bali1: "Semarang")];

List<Layout29ItemModel> layout29ItemList = [Layout29ItemModel(amanda:ImageConstant.imgShape70x70,amanda1: "Amanda"),Layout29ItemModel(amanda:ImageConstant.imgShape65,amanda1: "Anderson"),Layout29ItemModel(amanda:ImageConstant.imgShape66,amanda1: "Samantha"),Layout29ItemModel(amanda:ImageConstant.imgShape67,amanda1: "Andrew"),Layout29ItemModel(amanda:ImageConstant.imgShape68,amanda1: "Jakarta")];

List<HomeItemModel> homeItemList = [HomeItemModel(wingsTower:ImageConstant.imgShape160x144,favorite:ImageConstant.imgFavorite,price: " 220",month: "/month",wingsTower1: "Wings Tower",image:ImageConstant.imgSignalOrange3009x9,text: "4.9",jakartaIndonesia:ImageConstant.imgLinkedin,jakartaIndonesia1: "Jakarta, Indonesia"),HomeItemModel(wingsTower:ImageConstant.imgShape1,favorite:ImageConstant.imgFavoriteRedA200,price: " 290",month: "/month",wingsTower1: "Sky Dandelions",image:ImageConstant.imgSignalOrange3009x9,text: "4.9",jakartaIndonesia:ImageConstant.imgLinkedin,jakartaIndonesia1: "Jakarta, Indonesia"),HomeItemModel(wingsTower1: "Jakarta, Indonesia",image:ImageConstant.imgShape3)];

 }
