name: the_5_12_street_style___e_commerce_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.0.0
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Playfair Display
      fonts: 
        - asset: assets/fonts/PlayfairDisplaySemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplayItalicRegular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplayExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplayRomanBold.ttf
          weight: 700
