import 'models/set_your_fingerprint_model.dart';import 'package:flutter/material.dart';import 'package:the_5_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'provider/set_your_fingerprint_provider.dart';import 'package:the_5_16_tikpik___short_video__social_networking/presentation/account_setup_successful_dialog/account_setup_successful_dialog.dart';class SetYourFingerprintScreen extends StatefulWidget {const SetYourFingerprintScreen({Key? key}) : super(key: key);

@override SetYourFingerprintScreenState createState() =>  SetYourFingerprintScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SetYourFingerprintProvider(), child: SetYourFingerprintScreen()); } 
 }
class SetYourFingerprintScreenState extends State<SetYourFingerprintScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 48.v), child: Column(children: [SizedBox(height: 48.v), Container(width: 323.h, margin: EdgeInsets.symmetric(horizontal: 28.h), child: Text("msg_add_a_fingerprint".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLarge18.copyWith(height: 1.40))), Spacer(flex: 49), SizedBox(height: 193.v, width: 163.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 193.v, width: 163.h, child: CircularProgressIndicator(value: 0.5))), CustomImageView(imagePath: ImageConstant.imgVectorPrimary, height: 161.v, width: 136.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgVectorPrimary132x111, height: 132.v, width: 111.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgVectorPrimary99x84, height: 99.v, width: 84.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgVectorPrimary71x60, height: 71.v, width: 60.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgVectorPrimary37x32, height: 37.v, width: 32.h, alignment: Alignment.center)])), Spacer(flex: 50), Container(width: 324.h, margin: EdgeInsets.symmetric(horizontal: 27.h), child: Text("msg_please_put_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLarge18.copyWith(height: 1.40))), SizedBox(height: 73.v), _buildAutoLayoutHorizontal(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "msg_set_your_fingerprint".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_skip".tr, margin: EdgeInsets.only(right: 6.h), buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleMediumPrimary, onPressed: () {onTapSkip(context);})), Expanded(child: CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 6.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer16, onPressed: () {onTapContinue(context);}))]); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapSkip(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeContainerScreen, ); } 

/// Displays a dialog with the [AccountSetupSuccessfulDialog] content.
onTapContinue(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: AccountSetupSuccessfulDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
