import '../trending_hashtag_details_screen/widgets/autolayoutvertical4_item_widget.dart';import 'controller/trending_hashtag_details_controller.dart';import 'models/autolayoutvertical4_item_model.dart';import 'package:flutter/material.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_outlined_button.dart';class TrendingHashtagDetailsScreen extends GetWidget<TrendingHashtagDetailsController> {const TrendingHashtagDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 62.h), child: Row(children: [Container(height: 112.adaptSize, width: 112.adaptSize, padding: EdgeInsets.all(32.h), decoration: AppDecoration.fillDeepOrange.copyWith(borderRadius: BorderRadiusStyle.circleBorder56), child: CustomImageView(imagePath: ImageConstant.imgCategoriesHashtag, height: 48.adaptSize, width: 48.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 22.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_amazingfood".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 10.v), Text("lbl_827_5m_videos".tr, style: theme.textTheme.titleSmall), SizedBox(height: 13.v), CustomOutlinedButton(width: 184.h, text: "msg_add_to_favorites".tr, leftIcon: Container(margin: EdgeInsets.only(right: 2.h), child: CustomImageView(imagePath: ImageConstant.imgBookmarkPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonTextStyle: CustomTextStyles.titleSmallPrimaryBold)]))]))), SizedBox(height: 24.v), Divider(), SizedBox(height: 23.v), _buildAutoLayoutVertical()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "msg_trending_hashtag".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCategoriesShareGray900, margin: EdgeInsets.fromLTRB(24.h, 10.v, 24.h, 13.v))]); } 
/// Section Widget
Widget _buildAutoLayoutVertical() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 201.v, crossAxisCount: 3, mainAxisSpacing: 8.h, crossAxisSpacing: 8.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.trendingHashtagDetailsModelObj.value.autolayoutvertical4ItemList.value.length, itemBuilder: (context, index) {Autolayoutvertical4ItemModel model = controller.trendingHashtagDetailsModelObj.value.autolayoutvertical4ItemList.value[index]; return Autolayoutvertical4ItemWidget(model);})); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
