import '../sound_used_screen/widgets/soundused_item_widget.dart';import 'models/sound_used_model.dart';import 'models/soundused_item_model.dart';import 'package:flutter/material.dart';import 'package:the_5_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/custom_elevated_button.dart';import 'package:the_5_16_tikpik___short_video__social_networking/widgets/custom_outlined_button.dart';import 'provider/sound_used_provider.dart';class SoundUsedScreen extends StatefulWidget {const SoundUsedScreen({Key? key}) : super(key: key);

@override SoundUsedScreenState createState() =>  SoundUsedScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SoundUsedProvider(), child: SoundUsedScreen()); } 
 }
class SoundUsedScreenState extends State<SoundUsedScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(children: [_buildAutoLayoutHorizontal(context), SizedBox(height: 29.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 19.v), _buildTypeDefaultList(context), SizedBox(height: 24.v), Divider(), SizedBox(height: 23.v), _buildSoundUsed(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCategoriesShareGray900, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 36.h), child: Row(children: [SizedBox(height: 140.adaptSize, width: 140.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 140.adaptSize, width: 140.adaptSize, radius: BorderRadius.circular(24.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgOverflowMenu, height: 32.adaptSize, width: 32.adaptSize, radius: BorderRadius.circular(16.h), alignment: Alignment.center)])), Padding(padding: EdgeInsets.only(left: 22.h, top: 21.v, bottom: 24.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 181.h, child: Text("msg_beautiful_girl_by".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.20))), SizedBox(height: 11.v), Text("lbl_28_7m_videos".tr, style: theme.textTheme.titleSmall)]))]))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_play_song".tr, margin: EdgeInsets.only(right: 4.h), leftIcon: Container(margin: EdgeInsets.only(right: 4.h), child: CustomImageView(imagePath: ImageConstant.imgOverflowmenuPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonTextStyle: CustomTextStyles.titleSmallPrimary)), Expanded(child: CustomOutlinedButton(text: "msg_add_to_favorites".tr, margin: EdgeInsets.only(left: 4.h), leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgBookmarkPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonTextStyle: CustomTextStyles.titleSmallPrimary))]); } 
/// Section Widget
Widget _buildTypeDefaultList(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 200.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEllipse1, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Padding(padding: EdgeInsets.symmetric(vertical: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sean_kingston".tr, style: theme.textTheme.titleMedium), SizedBox(height: 5.v), Align(alignment: Alignment.center, child: Text("msg_professional_singer".tr, style: theme.textTheme.titleSmall))]))])), CustomElevatedButton(height: 32.v, width: 73.h, text: "lbl_follow".tr, margin: EdgeInsets.symmetric(vertical: 14.v))]); } 
/// Section Widget
Widget _buildSoundUsed(BuildContext context) { return Consumer<SoundUsedProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 201.v, crossAxisCount: 3, mainAxisSpacing: 8.h, crossAxisSpacing: 8.h), physics: NeverScrollableScrollPhysics(), itemCount: provider.soundUsedModelObj.soundusedItemList.length, itemBuilder: (context, index) {SoundusedItemModel model = provider.soundUsedModelObj.soundusedItemList[index]; return SoundusedItemWidget(model);});}); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
