import '../trending_now_screen/widgets/trendingnow2_item_widget.dart';import 'models/trendingnow2_item_model.dart';import 'notifier/trending_now_notifier.dart';import 'package:flutter/material.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_6_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';class TrendingNowScreen extends ConsumerStatefulWidget {const TrendingNowScreen({Key? key}) : super(key: key);

@override TrendingNowScreenState createState() =>  TrendingNowScreenState();

 }
class TrendingNowScreenState extends ConsumerState<TrendingNowScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(left: 24.h, top: 27.v, right: 24.h), child: Consumer(builder: (context, ref, _) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 248.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: BouncingScrollPhysics(), itemCount: ref.watch(trendingNowNotifier).trendingNowModelObj?.trendingnow2ItemList.length ?? 0, itemBuilder: (context, index) {Trendingnow2ItemModel model = ref.watch(trendingNowNotifier).trendingNowModelObj?.trendingnow2ItemList[index] ?? Trendingnow2ItemModel(); return Trendingnow2ItemWidget(model);});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "lbl_trending_now".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 13.v))]); } 
 }
