import 'package:flutter/material.dart';import 'package:the_7_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_16_tikpik___short_video__social_networking/widgets/custom_radio_button.dart';
// ignore_for_file: must_be_immutable
class LanguageScreen extends StatelessWidget {LanguageScreen({Key? key}) : super(key: key);

String radioGroup = "";

List<String> radioList = ["lbl_english_us", "lbl_english_uk"];

String language = "";

List<String> radioList1 = ["lbl_mandarin", "lbl_hindi", "lbl_spanish", "lbl_french", "lbl_arabic", "lbl_bengali", "lbl_russian"];

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 829.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 21.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 158.v), child: SizedBox(width: 380.h, child: Divider()))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Suggested", style: theme.textTheme.titleLarge), SizedBox(height: 31.v), _buildGroup386(context), SizedBox(height: 66.v), Text("Language", style: theme.textTheme.titleLarge), SizedBox(height: 21.v), _buildLanguage(context)])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Language", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildGroup386(BuildContext context) { return Column(children: [CustomRadioButton(width: 382.h, text: "English (US)", value: radioList[0], groupValue: radioGroup, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {radioGroup = value;}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "English (UK)", value: radioList[1], groupValue: radioGroup, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {radioGroup = value;}))]); } 
/// Section Widget
Widget _buildLanguage(BuildContext context) { return Column(children: [CustomRadioButton(width: 382.h, text: "Mandarin", value: radioList1[0], groupValue: language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "Hindi", value: radioList1[1], groupValue: language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "Spanish", value: radioList1[2], groupValue: language, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "French", value: radioList1[3], groupValue: language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "Arabic", value: radioList1[4], groupValue: language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "Bengali", value: radioList1[5], groupValue: language, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "Russian", value: radioList1[6], groupValue: language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {language = value;}))]); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
 }
