import '../property_details_screen/widgets/layout24_item_widget.dart';import '../property_details_screen/widgets/layout25_item_widget.dart';import '../property_details_screen/widgets/propertydetails_item_widget.dart';import '../property_details_screen/widgets/transactiontype_item_widget.dart';import '../property_details_screen/widgets/viewallreviews_item_widget.dart';import 'dart:async';import 'package:flutter/material.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';import 'package:the_7_17_housit___buyrentsell_property/core/app_export.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/appbar_trailing_iconbutton_four.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/app_bar/custom_app_bar.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_drop_down.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_elevated_button.dart';import 'package:the_7_17_housit___buyrentsell_property/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class PropertyDetailsScreen extends StatelessWidget {PropertyDetailsScreen({Key? key}) : super(key: key);

List<String> dropdownItemList = ["Item One", "Item Two", "Item Three"];

Completer<GoogleMapController> googleMapController = Completer();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [_buildPropertyOverview(context), SizedBox(height: 12.v), _buildTitle(context), SizedBox(height: 11.v), _buildLinkedin(context), SizedBox(height: 15.v), _buildLayout(context), SizedBox(height: 20.v), Divider(color: appTheme.blueGray50, indent: 23.h, endIndent: 24.h), SizedBox(height: 18.v), _buildItemOwner(context), SizedBox(height: 20.v), _buildLayout1(context), SizedBox(height: 37.v), _buildLocationPublicFacilities(context), SizedBox(height: 15.v), _buildLayout2(context), SizedBox(height: 15.v), _buildFrame(context), SizedBox(height: 39.v), _buildCostLiving(context), SizedBox(height: 43.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Reviews", style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildViewAllReviews(context), SizedBox(height: 47.v), _buildNearbyEstate(context), SizedBox(height: 25.v)]))))); } 
/// Section Widget
Widget _buildPropertyOverview(BuildContext context) { return SizedBox(height: 524.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgShape520x375, height: 520.v, width: 375.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(height: 518.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgShape518x375, height: 518.v, width: 375.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 50.v, leadingWidth: 74.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgTwitter, margin: EdgeInsets.only(left: 24.h)), AppbarTrailingIconbuttonFour(imagePath: ImageConstant.imgFavorite, margin: EdgeInsets.only(left: 15.h, right: 24.h))]), SizedBox(height: 230.v), CustomImageView(imagePath: ImageConstant.imgShape60x60, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(18.h), alignment: Alignment.centerRight), SizedBox(height: 5.v), CustomImageView(imagePath: ImageConstant.imgShape54, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(18.h), alignment: Alignment.centerRight), SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomElevatedButton(height: 50.v, width: 95.h, text: "4.9", margin: EdgeInsets.only(top: 10.v), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientRedAToSecondaryContainerDecoration, buttonTextStyle: CustomTextStyles.titleSmallMontserratWhiteA700), CustomElevatedButton(height: 50.v, width: 124.h, text: "Apartment", margin: EdgeInsets.only(left: 6.h, top: 10.v), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 18.v, width: 15.h)), buttonStyle: CustomButtonStyles.fillBlueGrayAa, buttonTextStyle: CustomTextStyles.bodySmallWhiteA700), Spacer(), SizedBox(height: 60.adaptSize, width: 60.adaptSize, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgShape55, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(18.h), alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 16.v), child: Text("+3", style: CustomTextStyles.titleMediumBluegray50)))]))])])))])))])); } 
/// Section Widget
Widget _buildTitle(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("Wings Tower", style: CustomTextStyles.headlineSmallBold)), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text(" 220", style: CustomTextStyles.headlineSmallBold))])); } 
/// Section Widget
Widget _buildLinkedin(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLinkedinDeepOrangeA20012x12, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Jakarta, Indonesia", style: theme.textTheme.bodyMedium))]), Text("per month", style: theme.textTheme.bodyMedium)])); } 
/// Section Widget
Widget _buildLayout(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Wrap(runSpacing: 9.v, spacing: 9.h, children: List<Widget>.generate(2, (index) => TransactiontypeItemWidget())), CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(14.h), onTap: () {onTapBtnSettings(context);}, child: CustomImageView(imagePath: ImageConstant.imgSettings50x50))])); } 
/// Section Widget
Widget _buildItemOwner(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgShape53x53, height: 53.adaptSize, width: 53.adaptSize, radius: BorderRadius.circular(26.h)), Padding(padding: EdgeInsets.only(left: 16.h, top: 4.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Anderson", style: CustomTextStyles.titleMedium16), SizedBox(height: 9.v), Text("Real Estate Agent", style: CustomTextStyles.titleSmallBluegray600)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgSettingsBlueGray8000120x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 17.v, right: 8.h, bottom: 16.v))])); } 
/// Section Widget
Widget _buildLayout1(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 50.v, child: ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: 3, itemBuilder: (context, index) {return Layout24ItemWidget();}))); } 
/// Section Widget
Widget _buildLocationPublicFacilities(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Location & Public Facilities", style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 1.h, right: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(15.h), child: CustomImageView(imagePath: ImageConstant.imgLinkedinBlueGray60050x50)), Expanded(child: Container(width: 254.h, margin: EdgeInsets.only(left: 15.h, top: 5.v, bottom: 2.v), child: Text("St. Cikoko Timur, Kec. Pancoran, Jakarta\nSelatan, Indonesia 12770", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.50))))])), SizedBox(height: 15.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 20.v, 21.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownPrimary, height: 10.adaptSize, width: 10.adaptSize)), hintText: "km from your location", hintStyle: theme.textTheme.titleSmall!, items: dropdownItemList, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 15.v, 30.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgLinkedin20x20, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 50.v), onChanged: (value) {})])); } 
/// Section Widget
Widget _buildLayout2(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 50.v, child: ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: 3, itemBuilder: (context, index) {return Layout25ItemWidget();}))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 235.v, width: 327.h, decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.bottomCenter, children: [SizedBox(height: 235.v, width: 327.h, child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 116.h, vertical: 16.v), decoration: AppDecoration.fillWhiteA, child: Text("View all on map", style: CustomTextStyles.bodySmallBluegray80001_1))), Align(alignment: Alignment.topLeft, child: Container(height: 113.v, width: 156.h, margin: EdgeInsets.only(left: 64.h, top: 41.v), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpOrange300, height: 51.v, width: 34.h, alignment: Alignment.topLeft), CustomImageView(imagePath: ImageConstant.imgVector7, height: 71.v, width: 120.h, radius: BorderRadius.circular(2.h), alignment: Alignment.bottomCenter), CustomImageView(imagePath: ImageConstant.imgPinRealEstate, height: 51.v, width: 34.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(bottom: 15.v))])))]))); } 
/// Section Widget
Widget _buildCostLiving(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Padding(padding: EdgeInsets.only(right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Cost of Living", style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text("view details", style: CustomTextStyles.labelLargePrimary))])), SizedBox(height: 14.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: CustomIconButton(height: 53.adaptSize, width: 53.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillBlueGrayTL17, child: CustomImageView(imagePath: ImageConstant.imgClose))), Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "", style: CustomTextStyles.titleMediumMontserratBold), TextSpan(text: " "), TextSpan(text: "830", style: CustomTextStyles.titleMediumMontserratBold), TextSpan(text: "/month*", style: CustomTextStyles.labelMediumSemiBold)]), textAlign: TextAlign.left), SizedBox(height: 9.v), SizedBox(width: 187.h, child: Text("*From average citizen spend around this location", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelMediumBluegray600_1.copyWith(height: 1.50)))]))]))])); } 
/// Section Widget
Widget _buildViewAllReviews(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: 4, itemBuilder: (context, index) {return ViewallreviewsItemWidget();})); } 
/// Section Widget
Widget _buildNearbyEstate(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Nearby From this Location", style: theme.textTheme.titleMedium), SizedBox(height: 14.v), GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 232.v, crossAxisCount: 1, mainAxisSpacing: 1.h, crossAxisSpacing: 1.h), physics: NeverScrollableScrollPhysics(), itemCount: 2, itemBuilder: (context, index) {return PropertydetailsItemWidget();})])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the viewScreen when the action is triggered.
onTapBtnSettings(BuildContext context) { Navigator.pushNamed(context, AppRoutes.viewScreen); } 
 }
