import 'controller/settings_controller.dart';import 'package:flutter/material.dart';import 'package:the_4_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_4_16_tikpik___short_video__social_networking/widgets/custom_switch.dart';import 'package:the_4_16_tikpik___short_video__social_networking/presentation/logout_modal_bottomsheet/logout_modal_bottomsheet.dart';import 'package:the_4_16_tikpik___short_video__social_networking/presentation/logout_modal_bottomsheet/controller/logout_modal_controller.dart';class SettingsScreen extends GetWidget<SettingsController> {const SettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(children: [_buildAutoLayoutHorizontal(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal2(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal3(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal5(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal6(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal7(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal8(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal9(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal10(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal11(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal12(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal13(), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: GestureDetector(onTap: () {onTapFortyNine();}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgUserRedA200, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_logout".tr, style: CustomTextStyles.titleMediumRedA200))]))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_settings".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLockGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_manage_account".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal1();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 108.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedLock, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_privacy".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal2() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal2();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedShield, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_security".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal3();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 122.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyLightOutlineScan, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_qr_code".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal4();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedMore, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_language".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_english_us".tr, style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal5() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEyeGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_dark_mode".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal6() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedVideo, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("msg_content_preferences".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal7() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTicket, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("lbl_ads".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal8() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedEdit, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("msg_report_a_problem".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal9() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 146.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedInfo, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_help_center".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal10() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 4.v), child: Text("lbl_safety_center".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal11() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurved3, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("msg_community_guidelines".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal12() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedPaper, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("msg_terms_of_services".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal13() { return GestureDetector(onTap: () {onTapAutoLayoutHorizontal5();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 159.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedDanger, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_privacy_policy".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the manageAccountsScreen when the action is triggered.
onTapAutoLayoutHorizontal() { Get.toNamed(AppRoutes.manageAccountsScreen, ); } 
/// Navigates to the privacyScreen when the action is triggered.
onTapAutoLayoutHorizontal1() { Get.toNamed(AppRoutes.privacyScreen, ); } 
/// Navigates to the securityScreen when the action is triggered.
onTapAutoLayoutHorizontal2() { Get.toNamed(AppRoutes.securityScreen, ); } 
/// Navigates to the qrCodeScreen when the action is triggered.
onTapAutoLayoutHorizontal3() { Get.toNamed(AppRoutes.qrCodeScreen, ); } 
/// Navigates to the languageScreen when the action is triggered.
onTapAutoLayoutHorizontal4() { Get.toNamed(AppRoutes.languageScreen, ); } 
/// Navigates to the privacyPolicyScreen when the action is triggered.
onTapAutoLayoutHorizontal5() { Get.toNamed(AppRoutes.privacyPolicyScreen, ); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [LogoutModalBottomsheet] widget.
///
/// The bottom sheet is controlled by the [LogoutModalController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapFortyNine() { Get.bottomSheet(LogoutModalBottomsheet(Get.put(LogoutModalController(),),),isScrollControlled: true,); } 
 }
