import 'bloc/home_bloc.dart';import 'models/home_model.dart';import 'package:flutter/material.dart';import 'package:the_3_21_vertex___real_estate_app/core/app_export.dart';import 'package:the_3_21_vertex___real_estate_app/presentation/home_search_page/home_search_page.dart';import 'package:the_3_21_vertex___real_estate_app/presentation/message_page/message_page.dart';import 'package:the_3_21_vertex___real_estate_app/presentation/my_home_page/my_home_page.dart';import 'package:the_3_21_vertex___real_estate_app/presentation/profile_page/profile_page.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_subtitle_five.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_title_image.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/custom_bottom_bar.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/custom_icon_button.dart';import 'package:the_3_21_vertex___real_estate_app/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class HomeScreen extends StatelessWidget {HomeScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { var arg = ModalRoute.of(context)?.settings.arguments as Map<String, dynamic>; return BlocProvider<HomeBloc>(create: (context) => HomeBloc(HomeState(homeModelObj: HomeModel(), token: arg[NavigationArgs.token], id: arg[NavigationArgs.id]))..add(HomeInitialEvent()), child: HomeScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [BlocSelector<HomeBloc, HomeState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search".tr);}), SizedBox(height: 24.v), _buildPropertyCard(context), SizedBox(height: 24.v), _buildPropertyCard(context)]))))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 60.v, title: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(children: [AppbarSubtitleFive(text: "lbl_location".tr, margin: EdgeInsets.only(right: 129.h)), SizedBox(height: 6.v), Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgIconMapPin, margin: EdgeInsets.only(bottom: 3.v)), AppbarSubtitleThree(text: "msg_st_celina_delaware".tr, margin: EdgeInsets.only(left: 8.h)), AppbarTitleImage(imagePath: ImageConstant.imgArrowDownBlueGray500, margin: EdgeInsets.only(left: 4.h, top: 2.v, bottom: 5.v))])])), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgGrid, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 10.h)), AppbarTrailingIconbutton(imagePath: ImageConstant.imgNotificationLight, margin: EdgeInsets.only(left: 12.h, top: 10.v, right: 34.h), onTap: () {onTapNotificationLight(context);})], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Common widget
Widget _buildPropertyCard(BuildContext context, {Function? onTapImg, }) { return SizedBox(height: 418.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImg418x327, height: 418.v, width: 327.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center, onTap: () {onTapImg!.call();}), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.outlineGrayTL18, alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgFavorite)), SizedBox(height: 268.v), Container(padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.fillGray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_golden_meadows".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgIconMapPin, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_st_celina_delaware2".tr, style: theme.textTheme.bodySmall))])])), Padding(padding: EdgeInsets.only(top: 1.v), child: Column(children: [Align(alignment: Alignment.centerRight, child: Text("lbl_500".tr, style: CustomTextStyles.titleMediumPrimary_1)), SizedBox(height: 9.v), Text("lbl_per_month".tr, style: theme.textTheme.bodySmall)]))]))])))])); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return "/"; case BottomBarEnum.Message: return AppRoutes.messagePage; case BottomBarEnum.Discover: return AppRoutes.homeSearchPage; case BottomBarEnum.Myhome: return AppRoutes.myHomePage; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.messagePage: return MessagePage(); case AppRoutes.homeSearchPage: return HomeSearchPage(); case AppRoutes.myHomePage: return MyHomePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the notificationScreen when the action is triggered.
onTapNotificationLight(BuildContext context) { NavigatorService.pushNamed(AppRoutes.notificationScreen, ); } 
/// Navigates to the productDetailsScreen when the action is triggered.
onTapImgImg(BuildContext context) { NavigatorService.pushNamed(AppRoutes.productDetailsScreen, ); } 
/// Navigates to the productDetailsScreen when the action is triggered.
onTapImgImg1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.productDetailsScreen, ); } 
 }
