import 'models/add_new_property_home_facts_model.dart';import 'package:flutter/material.dart';import 'package:the_5_21_vertex___real_estate_app/core/app_export.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/custom_drop_down.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/custom_elevated_button.dart';import 'package:the_5_21_vertex___real_estate_app/widgets/custom_text_form_field.dart';import 'provider/add_new_property_home_facts_provider.dart';class AddNewPropertyHomeFactsScreen extends StatefulWidget {const AddNewPropertyHomeFactsScreen({Key? key}) : super(key: key);

@override AddNewPropertyHomeFactsScreenState createState() =>  AddNewPropertyHomeFactsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => AddNewPropertyHomeFactsProvider(), child: AddNewPropertyHomeFactsScreen()); } 
 }
class AddNewPropertyHomeFactsScreenState extends State<AddNewPropertyHomeFactsScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 5.v), child: Column(children: [_buildAddressAndProgress(context), SizedBox(height: 16.v), Container(height: 6.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray300, borderRadius: BorderRadius.circular(3.h)), child: ClipRRect(borderRadius: BorderRadius.circular(3.h), child: LinearProgressIndicator(value: 0.75, backgroundColor: appTheme.gray300, valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_home_facts".tr, style: CustomTextStyles.titleMediumBold_1)), SizedBox(height: 9.v), Container(width: 321.h, margin: EdgeInsets.only(right: 6.h), child: Text("msg_this_helps_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.50))), SizedBox(height: 16.v), _buildTypeProperty(context), SizedBox(height: 13.v), _buildInputs(context), SizedBox(height: 17.v), _buildInputs1(context), SizedBox(height: 17.v), _buildInputs2(context), SizedBox(height: 18.v), _buildTypeProperty1(context)]))))])), bottomNavigationBar: _buildBTN(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_add_new_property".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildAddressAndProgress(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Text("lbl_home_facts".tr, style: theme.textTheme.titleSmall)), CustomElevatedButton(height: 33.v, width: 79.h, text: "lbl_06_08".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700)]); } 
/// Section Widget
Widget _buildTypeProperty(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_type_property".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), Selector<AddNewPropertyHomeFactsProvider, AddNewPropertyHomeFactsModel?>(selector: (context, provider) => provider.addNewPropertyHomeFactsModelObj, builder: (context, addNewPropertyHomeFactsModelObj, child) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 14.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownPrimarycontainer, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_select_type".tr, hintStyle: CustomTextStyles.titleSmallBluegray500Medium, items: addNewPropertyHomeFactsModelObj?.dropdownItemList ?? [], borderDecoration: DropDownStyleHelper.fillGray, fillColor: appTheme.gray300, onChanged: (value) {context.read<AddNewPropertyHomeFactsProvider>().onSelected(value);});})]); } 
/// Section Widget
Widget _buildInputs(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(children: [_buildTitle(context, fullBaths: "msg_finished_sq_ft".tr), SizedBox(height: 6.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController, builder: (context, inputFieldsController, child) {return CustomTextFormField(width: 158.h, controller: inputFieldsController, hintText: "lbl_0".tr);})]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_lot_size".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController1, builder: (context, inputFieldsController1, child) {return CustomTextFormField(width: 158.h, controller: inputFieldsController1, hintText: "lbl_0".tr);})])))]); } 
/// Section Widget
Widget _buildInputs1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_year_built".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController2, builder: (context, inputFieldsController2, child) {return CustomTextFormField(width: 158.h, controller: inputFieldsController2, hintText: "lbl_0".tr);})]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bedrooms".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController3, builder: (context, inputFieldsController3, child) {return CustomTextFormField(width: 158.h, controller: inputFieldsController3, hintText: "lbl_0".tr);})])))]); } 
/// Section Widget
Widget _buildInputs2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(children: [_buildTitle(context, fullBaths: "lbl_full_baths".tr), SizedBox(height: 7.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController4, builder: (context, inputFieldsController4, child) {return CustomTextFormField(width: 158.h, controller: inputFieldsController4, hintText: "lbl_0".tr);})]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [_buildTitle(context, fullBaths: "msg_security_deposit".tr), SizedBox(height: 6.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.priceController, builder: (context, priceController, child) {return CustomTextFormField(width: 158.h, controller: priceController, hintText: "lbl_02".tr);})])))]); } 
/// Section Widget
Widget _buildTypeProperty1(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_monthly_rent".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), Selector<AddNewPropertyHomeFactsProvider, TextEditingController?>(selector: (context, provider) => provider.priceController1, builder: (context, priceController1, child) {return CustomTextFormField(controller: priceController1, hintText: "lbl_02".tr, textInputAction: TextInputAction.done);})]); } 
/// Section Widget
Widget _buildBTN(BuildContext context) { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), decoration: AppDecoration.outlineBlueGrayF, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNext(context);})); } 
/// Common widget
Widget _buildTitle(BuildContext context, {required String fullBaths, }) { return SizedBox(width: 158.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(fullBaths, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.blueGray500)), CustomImageView(imagePath: ImageConstant.imgVideoCamera, height: 16.adaptSize, width: 16.adaptSize)])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the addNewPropertyContactScreen when the action is triggered.
onTapNext(BuildContext context) { NavigatorService.pushNamed(AppRoutes.addNewPropertyContactScreen, ); } 
 }
