import 'bloc/language_bloc.dart';import 'models/language_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_radio_button.dart';class LanguageScreen extends StatelessWidget {const LanguageScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<LanguageBloc>(create: (context) => LanguageBloc(LanguageState(languageModelObj: LanguageModel()))..add(LanguageInitialEvent()), child: LanguageScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 829.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 21.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 158.v), child: SizedBox(width: 380.h, child: Divider()))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_suggested".tr, style: theme.textTheme.titleLarge), SizedBox(height: 31.v), _buildGroup386(context), SizedBox(height: 66.v), Text("lbl_language".tr, style: theme.textTheme.titleLarge), SizedBox(height: 21.v), _buildLanguage(context)])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_language".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildGroup386(BuildContext context) { return BlocBuilder<LanguageBloc, LanguageState>(builder: (context, state) {return state.languageModelObj!.radioList.isNotEmpty ? Column(children: [CustomRadioButton(width: 382.h, text: "lbl_english_us".tr, value: state.languageModelObj?.radioList[0] ?? "", groupValue: state.radioGroup, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButtonEvent(value: value));}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_english_uk".tr, value: state.languageModelObj?.radioList[1] ?? "", groupValue: state.radioGroup, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButtonEvent(value: value));}))]) : Container();}); } 
/// Section Widget
Widget _buildLanguage(BuildContext context) { return BlocBuilder<LanguageBloc, LanguageState>(builder: (context, state) {return state.languageModelObj!.radioList1.isNotEmpty ? Column(children: [CustomRadioButton(width: 382.h, text: "lbl_mandarin".tr, value: state.languageModelObj?.radioList1[0] ?? "", groupValue: state.language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));}), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_hindi".tr, value: state.languageModelObj?.radioList1[1] ?? "", groupValue: state.language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_spanish".tr, value: state.languageModelObj?.radioList1[2] ?? "", groupValue: state.language, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "lbl_french".tr, value: state.languageModelObj?.radioList1[3] ?? "", groupValue: state.language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_arabic".tr, value: state.languageModelObj?.radioList1[4] ?? "", groupValue: state.language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 22.v), child: CustomRadioButton(width: 382.h, text: "lbl_bengali".tr, value: state.languageModelObj?.radioList1[5] ?? "", groupValue: state.language, textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 382.h, text: "lbl_russian".tr, value: state.languageModelObj?.radioList1[6] ?? "", groupValue: state.language, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleMediumSemiBold_1, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));}))]) : Container();}); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
