import 'models/edit_profile_model.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:flutter/material.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/core/utils/validation_functions.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/custom_drop_down.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/custom_elevated_button.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/custom_phone_number.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/custom_text_form_field.dart';import 'provider/edit_profile_provider.dart';class EditProfileScreen extends StatefulWidget {const EditProfileScreen({Key? key}) : super(key: key);

@override EditProfileScreenState createState() =>  EditProfileScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => EditProfileProvider(), child: EditProfileScreen()); } 
 }

// ignore_for_file: must_be_immutable
class EditProfileScreenState extends State<EditProfileScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [_buildInputFields(context), SizedBox(height: 24.v), _buildInputFields1(context), SizedBox(height: 24.v), _buildDate(context), SizedBox(height: 24.v), _buildEmail(context), SizedBox(height: 24.v), _buildPhoneNumber(context), SizedBox(height: 24.v), Selector<EditProfileProvider, EditProfileModel?>(selector: (context, provider) => provider.editProfileModelObj, builder: (context, editProfileModelObj, child) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconBottom, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_male".tr, items: editProfileModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v), borderDecoration: DropDownStyleHelper.fillGrayTL16, fillColor: appTheme.gray100, onChanged: (value) {context.read<EditProfileProvider>().onSelected(value);});}), SizedBox(height: 5.v)]))))), bottomNavigationBar: _buildUpdate(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_edit_profile".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildInputFields(BuildContext context) { return Selector<EditProfileProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController, builder: (context, inputFieldsController, child) {return CustomTextFormField(controller: inputFieldsController, hintText: "lbl_andrew_ainsley".tr);}); } 
/// Section Widget
Widget _buildInputFields1(BuildContext context) { return Selector<EditProfileProvider, TextEditingController?>(selector: (context, provider) => provider.inputFieldsController1, builder: (context, inputFieldsController1, child) {return CustomTextFormField(controller: inputFieldsController1, hintText: "lbl_andrew".tr);}); } 
/// Section Widget
Widget _buildDate(BuildContext context) { return Selector<EditProfileProvider, TextEditingController?>(selector: (context, provider) => provider.dateController, builder: (context, dateController, child) {return CustomTextFormField(controller: dateController, hintText: "lbl_27_12_1995".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v));}); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return Selector<EditProfileProvider, TextEditingController?>(selector: (context, provider) => provider.emailController, builder: (context, emailController, child) {return CustomTextFormField(controller: emailController, hintText: "lbl_user_domain_com".tr, textInputType: TextInputType.emailAddress, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary20x20, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v));}); } 
/// Section Widget
Widget _buildPhoneNumber(BuildContext context) { return Consumer<EditProfileProvider>(builder: (context, provider, child) {return CustomPhoneNumber(country: provider.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: provider.phoneNumberController, onTap: (Country value) {context.read<EditProfileProvider>().changeCountry(value);});}); } 
/// Section Widget
Widget _buildUpdate(BuildContext context) { return CustomElevatedButton(text: "lbl_update".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapUpdate(context);}); } 
/// Navigates to the profileDetailsOneScreen when the action is triggered.
onTapUpdate(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileDetailsOneScreen, ); } 
 }
