import '../home_page/widgets/home_item_widget.dart';import '../home_page/widgets/layout27_item_widget.dart';import '../home_page/widgets/layout28_item_widget.dart';import '../home_page/widgets/layout29_item_widget.dart';import '../home_page/widgets/promotionbanner_item_widget.dart';import 'models/home_item_model.dart';import 'models/home_model.dart';import 'models/layout27_item_model.dart';import 'models/layout28_item_model.dart';import 'models/layout29_item_model.dart';import 'models/promotionbanner_item_model.dart';import 'package:flutter/material.dart';import 'package:the_5_17_housit___buyrentsell_property/core/app_export.dart';import 'provider/home_provider.dart';class HomePage extends StatefulWidget {const HomePage({Key? key}) : super(key: key);

@override HomePageState createState() =>  HomePageState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => HomeProvider(), child: HomePage()); } 
 }
class HomePageState extends State<HomePage> with  AutomaticKeepAliveClientMixin<HomePage> {@override bool get wantKeepAlive =>  true;

@override void initState() { super.initState();// TODO: implement Actions
NavigatorService.pushNamed(AppRoutes.transactionTabContainerPage, );NavigatorService.pushNamed(AppRoutes.verticalPage, );NavigatorService.pushNamed(AppRoutes.exampleDataPage, ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 18.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildPromotionBanner(context), SizedBox(height: 37.v), _buildItemHeader(context), SizedBox(height: 16.v), _buildLayout(context), SizedBox(height: 39.v), _buildItemHeader1(context), SizedBox(height: 14.v), _buildLayout1(context), SizedBox(height: 39.v), _buildItemHeader2(context), SizedBox(height: 14.v), _buildLayout2(context), SizedBox(height: 33.v), Text("msg_explore_nearby_estates".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), _buildHome(context)])))]))))); } 
/// Section Widget
Widget _buildPromotionBanner(BuildContext context) { return SizedBox(height: 180.v, child: Consumer<HomeProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: provider.homeModelObj.promotionbannerItemList.length, itemBuilder: (context, index) {PromotionbannerItemModel model = provider.homeModelObj.promotionbannerItemList[index]; return PromotionbannerItemWidget(model, onTapItemPromotion: () {onTapItemPromotion(context);});});})); } 
/// Section Widget
Widget _buildItemHeader(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_featured_estates".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: Text("lbl_view_all".tr, style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildLayout(BuildContext context) { return SizedBox(height: 156.v, child: Consumer<HomeProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: provider.homeModelObj.layout27ItemList.length, itemBuilder: (context, index) {Layout27ItemModel model = provider.homeModelObj.layout27ItemList[index]; return Layout27ItemWidget(model);});})); } 
/// Section Widget
Widget _buildItemHeader1(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 50.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_top_locations".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 4.v), child: Text("lbl_explore".tr, style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildLayout1(BuildContext context) { return SizedBox(height: 56.v, child: Consumer<HomeProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 4.h);}, itemCount: provider.homeModelObj.layout28ItemList.length, itemBuilder: (context, index) {Layout28ItemModel model = provider.homeModelObj.layout28ItemList[index]; return Layout28ItemWidget(model);});})); } 
/// Section Widget
Widget _buildItemHeader2(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_top_estate_agent".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 4.v), child: Text("lbl_explore".tr, style: CustomTextStyles.labelLargePrimary))])); } 
/// Section Widget
Widget _buildLayout2(BuildContext context) { return SizedBox(height: 96.v, child: Consumer<HomeProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 15.h);}, itemCount: provider.homeModelObj.layout29ItemList.length, itemBuilder: (context, index) {Layout29ItemModel model = provider.homeModelObj.layout29ItemList[index]; return Layout29ItemWidget(model);});})); } 
/// Section Widget
Widget _buildHome(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 24.h), child: Consumer<HomeProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 232.v, crossAxisCount: 2, mainAxisSpacing: 7.h, crossAxisSpacing: 7.h), physics: NeverScrollableScrollPhysics(), itemCount: provider.homeModelObj.homeItemList.length, itemBuilder: (context, index) {HomeItemModel model = provider.homeModelObj.homeItemList[index]; return HomeItemWidget(model, onTapEstatesCardVertical: () {onTapEstatesCardVertical(context);});});})); } 
/// Navigates to the promotionScreen when the action is triggered.
onTapItemPromotion(BuildContext context) { NavigatorService.pushNamed(AppRoutes.promotionScreen); } 
/// Navigates to the propertyDetailsScreen when the action is triggered.
onTapEstatesCardVertical(BuildContext context) { NavigatorService.pushNamed(AppRoutes.propertyDetailsScreen); } 
 }
