import 'models/notification_settings_model.dart';import 'package:flutter/material.dart';import 'package:the_5_07_comfort___hotel_booking_app/core/app_export.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/app_bar/custom_app_bar.dart';import 'package:the_5_07_comfort___hotel_booking_app/widgets/custom_switch.dart';import 'provider/notification_settings_provider.dart';class NotificationSettingsScreen extends StatefulWidget {const NotificationSettingsScreen({Key? key}) : super(key: key);

@override NotificationSettingsScreenState createState() =>  NotificationSettingsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => NotificationSettingsProvider(), child: NotificationSettingsScreen()); } 
 }
class NotificationSettingsScreenState extends State<NotificationSettingsScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Column(children: [_buildAutoLayoutHorizontal(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal2(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal3(context), SizedBox(height: 30.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 31.v), _buildAutoLayoutHorizontal5(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_notifications".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("msg_general_notification".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch, builder: (context, isSelectedSwitch, child) {return CustomSwitch(value: isSelectedSwitch, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox1(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_sound".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch1, builder: (context, isSelectedSwitch1, child) {return CustomSwitch(value: isSelectedSwitch1, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox2(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_vibrate".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch2, builder: (context, isSelectedSwitch2, child) {return CustomSwitch(value: isSelectedSwitch2, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox3(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_app_updates".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch3, builder: (context, isSelectedSwitch3, child) {return CustomSwitch(value: isSelectedSwitch3, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox4(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("msg_new_service_available".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch4, builder: (context, isSelectedSwitch4, child) {return CustomSwitch(value: isSelectedSwitch4, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox5(value);});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal5(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_new_tips_available".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Selector<NotificationSettingsProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch5, builder: (context, isSelectedSwitch5, child) {return CustomSwitch(value: isSelectedSwitch5, onChange: (value) {context.read<NotificationSettingsProvider>().changeSwitchBox6(value);});})]); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
