import 'bloc/privacy_bloc.dart';import 'models/privacy_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_switch.dart';class PrivacyScreen extends StatelessWidget {const PrivacyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PrivacyBloc>(create: (context) => PrivacyBloc(PrivacyState(privacyModelObj: PrivacyModel()))..add(PrivacyInitialEvent()), child: PrivacyScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 21.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_discoverability".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 22.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 24.v), _buildIconlyCurvedSwap(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal2(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_personalization".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 24.v), _buildAutoLayoutHorizontal3(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal4(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal5(context), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_safety".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 22.v), _buildAutoLayoutHorizontal6(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal7(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal8(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal9(context), SizedBox(height: 24.v), _buildAutoLayoutHorizontal10(context), SizedBox(height: 2.v)])), bottomNavigationBar: _buildAutoLayoutHorizontal11(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 14.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_privacy".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEyeGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text("lbl_private_account".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), BlocSelector<PrivacyBloc, PrivacyState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(value: isSelectedSwitch, onChange: (value) {context.read<PrivacyBloc>().add(ChangeSwitchEvent(value: value));});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("msg_suggest_account".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 92.h, top: 4.v, bottom: 4.v))]); } 
/// Section Widget
Widget _buildIconlyCurvedSwap(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("msg_sync_contacts".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgGroupGray900, height: 11.v, width: 5.h, margin: EdgeInsets.symmetric(vertical: 8.v))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedLocation, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text("msg_location_services".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal3(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTicket, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("msg_ads_personalization".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 159.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgTwitterGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_quick_upload".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), BlocSelector<PrivacyBloc, PrivacyState, bool?>(selector: (state) => state.isSelectedSwitch1, builder: (context, isSelectedSwitch1) {return CustomSwitch(value: isSelectedSwitch1, onChange: (value) {context.read<PrivacyBloc>().add(ChangeSwitch1Event(value: value));});})]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal5(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDownload, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("msg_download_your_data".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal6(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgDownload, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_downloads".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal7(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 138.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedChat, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("lbl_comments2".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal8(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLockGray900, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_mentions_tags".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal9(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 157.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurved3, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_following_list".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal10(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 2.v), child: Text("lbl_duet".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal11(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 12.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 144.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedHeart, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_liked_video".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
