import '../trending_now_screen/widgets/trendingnow2_item_widget.dart';import 'models/trending_now_model.dart';import 'models/trendingnow2_item_model.dart';import 'package:flutter/material.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/core/app_export.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_leading_image.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_title.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_5_18_tune_cast___music_streaming__podcast_app/widgets/app_bar/custom_app_bar.dart';import 'provider/trending_now_provider.dart';class TrendingNowScreen extends StatefulWidget {const TrendingNowScreen({Key? key}) : super(key: key);

@override TrendingNowScreenState createState() =>  TrendingNowScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => TrendingNowProvider(), child: TrendingNowScreen()); } 
 }
class TrendingNowScreenState extends State<TrendingNowScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(left: 24.h, top: 27.v, right: 24.h), child: Consumer<TrendingNowProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 248.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: BouncingScrollPhysics(), itemCount: provider.trendingNowModelObj.trendingnow2ItemList.length, itemBuilder: (context, index) {Trendingnow2ItemModel model = provider.trendingNowModelObj.trendingnow2ItemList[index]; return Trendingnow2ItemWidget(model);});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "lbl_trending_now".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 13.v))]); } 
 }
