import 'bloc/send_message_bloc.dart';import 'models/send_message_model.dart';import 'package:flutter/material.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/app_export.dart';import 'package:the_3_16_tikpik___short_video__social_networking/core/utils/validation_functions.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_leading_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_title.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/appbar_trailing_image.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/app_bar/custom_app_bar.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_icon_button.dart';import 'package:the_3_16_tikpik___short_video__social_networking/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SendMessageScreen extends StatelessWidget {SendMessageScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SendMessageBloc>(create: (context) => SendMessageBloc(SendMessageState(sendMessageModelObj: SendMessageModel()))..add(SendMessageInitialEvent()), child: SendMessageScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h)), SizedBox(height: 14.v), Text("lbl_jenny_wilson2".tr, style: theme.textTheme.titleLarge), SizedBox(height: 9.v), Text("msg_actress_singer".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 19.v), Align(alignment: Alignment.centerRight, child: Container(width: 300.h, margin: EdgeInsets.only(left: 80.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 11.v), decoration: AppDecoration.gradientDeepOrangeAToOrange.copyWith(borderRadius: BorderRadiusStyle.customBorderTL16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [RichText(text: TextSpan(children: [TextSpan(text: "msg_hi_jenny_good_morning2".tr, style: CustomTextStyles.bodyLargeOnErrorContainer), TextSpan(text: "lbl".tr, style: CustomTextStyles.bodyLargeOnErrorContainer)]), textAlign: TextAlign.left), SizedBox(height: 7.v), Align(alignment: Alignment.centerRight, child: Text("lbl_10_01".tr, style: theme.textTheme.bodySmall))]))), SizedBox(height: 10.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 80.h), padding: EdgeInsets.symmetric(horizontal: 20.h), decoration: AppDecoration.gradientDeepOrangeAToOrange.copyWith(borderRadius: BorderRadiusStyle.customBorderTL16), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Container(width: 220.h, margin: EdgeInsets.only(top: 12.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_i_m_your_fan_i2".tr, style: CustomTextStyles.bodyLargeOnErrorContainer.copyWith(height: 1.40)), TextSpan(text: "lbl2".tr, style: CustomTextStyles.bodyLargeOnErrorContainer)]), textAlign: TextAlign.left))), Padding(padding: EdgeInsets.only(left: 15.h, top: 54.v, bottom: 11.v), child: Text("lbl_10_01".tr, style: theme.textTheme.bodySmall))]))), SizedBox(height: 5.v)]))))), bottomNavigationBar: _buildAutoLayoutHorizontal(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_jenny_wilson3".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewindGray900, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 13.h)), AppbarTrailingImage(imagePath: ImageConstant.imgIconlyCurvedCall, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 13.h)), AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray900, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 37.h))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 36.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: BlocSelector<SendMessageBloc, SendMessageState, TextEditingController?>(selector: (state) => state.messageController, builder: (context, messageController) {return CustomTextFormField(controller: messageController, hintText: "lbl_message2".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true, contentPadding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 19.v));})), Padding(padding: EdgeInsets.only(left: 12.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.gradientDeepOrangeAToOrange, child: CustomImageView(imagePath: ImageConstant.imgAutoLayoutHorizontalOnerrorcontainer)))])); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
